---
docker:
  data_root: /home/_docker_data_root

k8s_binary_install_from_url:
  # https://github.com/kubernetes-sigs/kind/releases
  - name: kind
    version: "0.20.0"
    version_command: kind --version
    path: /usr/local/bin/kind
    url: https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
    checksum: sha256:513a7213d6d3332dd9ef27c24dab35e5ef10a04fa27274fe1c14d8a246493ded
    unpack: false
  # https://github.com/helm/helm/releases
  - name: helm
    version: "3.11.1"
    version_command: helm version --short
    path: /usr/local/bin/helm
    url: https://get.helm.sh/helm-v3.11.1-linux-amd64.tar.gz
    checksum: sha256:0b1be96b66fab4770526f136f5f1a385a47c41923d33aab0dcb500e0f6c1bf7c
    unpack: true
  # https://github.com/helmfile/helmfile/releases
  - name: helmfile
    version: "0.157.0"
    version_command: helmfile -v | awk '{print $3}'
    path: /usr/local/bin/helmfile
    url: https://github.com/helmfile/helmfile/releases/download/v0.157.0/helmfile_0.157.0_linux_amd64.tar.gz
    checksum: sha256:0b2d9f603752b51e7b3a23cb2784c334c920cb6ed5f83ac6df6c29c8be5a75ae
    unpack: true
  # https://github.com/arttor/helmify/releases
  - name: helmify
    version: "0.3.22"
    version_command: helmify -version | grep Version | awk -F' ' '{print $2}'
    path: /usr/local/bin/helmify
    url: https://github.com/arttor/helmify/releases/download/v0.3.22/helmify_0.3.22_Linux_64-bit.tar.gz
    checksum: sha256:6ae7fa6726fd09a39d1b60c4ce7df7edc3fb4fbee2fc99211c217870cf8d226b
    unpack: true
  # https://github.com/derailed/k9s/releases
  - name: k9s
    version: "v0.50.6"
    version_command: "k9s version"
    path: "/usr/local/bin/k9s"
    url: "https://github.com/derailed/k9s/releases/download/v0.50.6/k9s_Linux_amd64.tar.gz"
    checksum: "sha256:5fc98f2dcf1d8fac6251f5a1ae1dc6fe7fe2b2d43b13bb3039e51ad492e2a70e"
    unpack: true
  # https://github.com/k3d-io/k3d/releases
  - name: k3d
    version: "v5.8.3"
    version_command: "k3d version"
    path: "/usr/local/bin/k3d"
    url: "https://github.com/k3d-io/k3d/releases/download/v5.8.3/k3d-linux-amd64"
    checksum: "sha256:dbaa79a76ace7f4ca230a1ff41dc7d8a5036a8ad0309e9c54f9bf3836dbe853e"
    unpack: false
