---
# see https://firmaelectronica.gob.es/Home/Descargas.html
- name: Install some manual dependencies
  become: true
  ansible.builtin.apt:
    name: icedtea-netx
    state: latest

- name: Install autofirma deb package
  become: true
  ansible.builtin.apt:
    deb: "{{ role_path }}/files/deb/autofirma_1.8.3.deb"
