---
# see https://chirp.danplanet.com/projects/chirp/wiki/Home
- name: Install CHIRP
  tags:
    - desktop
    - chirp
  become: true
  ansible.builtin.apt:
    package: chirp
    state: latest
  # this package may not be in the archive
  # don't stop the playbook if that is the case
  ignore_errors: true

# so we can use /dev/ttyUSB0 and /dev/ttyS0 as user
- name: Add user to dialout Unix group
  become: true
  ansible.builtin.user:
    name: "{{ user }}"
    groups: dialout
    append: true
