- name: install common desktop packages
  tags: desktop
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - firefox-esr
    - thunderbird
    - gimp
    - dia
    - pdfsam
    - terminator

- name: install terminator configuration
  include_tasks: "{{ role_path }}/../dotfiles/tasks/link_dotfiles.yml"
  vars:
    dotfiles:
      - config/terminator/config
