---
- name: Install common desktop packages
  tags: apt
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - firefox-esr
      - thunderbird
      - thunderbird-l10n-es-es
      - gimp
      - dia
      - pdfsam
      - gnome-calculator
      - conky-std
      - blueman
      - nautilus-dropbox
      - hexchat
      - mkdocs
      - mkdocs-material
      - copyq
      - amberol
      - vlc

- name: Install copyq config
  ansible.builtin.include_tasks: "{{ role_path }}/../dotfiles/tasks/link_dotfiles.yml"
  vars:
    dotfiles:
      - config/copyq/copyq.conf

- name: Install bitwarden desktop
  tags: bitwarden
  become: true
  ansible.builtin.apt:
    deb: https://vault.bitwarden.com/download/?app=desktop&platform=linux&variant=deb

- name: Install desktop backgrounds
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /usr/share/backgrounds/
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
  with_fileglob:
    - "backgrounds/*"

- name: Deinstall some packages
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - exfalso
      - quodlibet
      - xfburn
      - parole
      - mpv
