---
- name: Install desktop display related packages
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - autorandr
      # required by nvidia stuff
      - linux-headers-amd64

- name: Install autorandr config files
  ansible.builtin.include_tasks: "{{ role_path }}/../dotfiles/tasks/link_dotfiles.yml"
  when: ansible_facts['nodename'] in allowed_nodenames
  vars:
    dotfiles:
      - config/autorandr/3screens_{{ ansible_facts['nodename'] }}/config
      - config/autorandr/3screens_{{ ansible_facts['nodename'] }}/setup
    allowed_nodenames:
      - nostromo
      - endurance

# from https://www.startech.com/en-us/universal-laptop-docking-stations/dk30a2dh
- name: Install startech docking station driver
  include_tasks: "{{ role_path }}/../common/tasks/apt-install-from-repository.yml"
  vars:
    conf:
      shortname: startech-displaylink-driver
      repo_spec: https://www.synaptics.com/sites/default/files/Ubuntu stable main non-free
      key_path: "{{ role_path }}/files/synaptics-repository-keyring.gpg"
      key_extension: gpg
      packages:
        - displaylink-driver
