---
- name: Install lightdm-related packages
  tags: lightdm
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - light-locker
      # seems to be required, see https://bugs.debian.org/837979
      - accountsservice

- name: Install /etc/lightdm/lightdm.conf
  tags: lightdm
  become: true
  ansible.builtin.template:
    src: lightdm.conf.j2
    dest: /etc/lightdm/lightdm.conf
    owner: root
    group: root
    mode: "0644"
