---
- name: Include common desktop tasks
  ansible.builtin.include_tasks: common.yml

- name: Include lighdm tasks
  ansible.builtin.include_tasks: lightdm.yml

- name: Include desktop profiler tasks
  ansible.builtin.include_tasks: profiler.yml

- name: Include system sleep laptop suspend workaround
  ansible.builtin.include_tasks: laptop_suspend.yaml

- name: Include spotify tasks
  ansible.builtin.include_tasks: spotify.yml

- name: Include signal tasks
  ansible.builtin.include_tasks: signal.yaml

- name: Include slack tasks
  ansible.builtin.include_tasks: slack.yaml

- name: Include telegram tasks
  ansible.builtin.include_tasks: telegram.yaml

- name: Include autofirma tasks
  ansible.builtin.include_tasks: autofirma.yaml

- name: Include vscode tasks
  ansible.builtin.include_tasks: vscode.yaml

- name: Include CHIRP tasks
  ansible.builtin.include_tasks: chirp.yaml

- name: Include zoom tasks
  ansible.builtin.include_tasks: zoom.yaml

- name: Include bluetooth tasks
  ansible.builtin.include_tasks: bluetooth.yaml

- name: Include xfce tasks
  ansible.builtin.include_tasks: xfce.yaml

- name: Include stremio tasks
  ansible.builtin.include_tasks: stremio.yaml
