---
- name: Include common desktop tasks
  ansible.builtin.include_tasks: common.yml

- name: Include lighdm tasks
  ansible.builtin.include_tasks: lightdm.yml

- name: Include desktop profiler tasks
  ansible.builtin.include_tasks: profiler.yml

- name: Include spotify tasks
  ansible.builtin.include_tasks: spotify.yml

- name: Include signal tasks
  ansible.builtin.include_tasks: signal.yaml

- name: Include slack tasks
  ansible.builtin.include_tasks: slack.yaml

- name: Include telegram tasks
  ansible.builtin.include_tasks: telegram.yaml

- name: Include autofirma tasks
  ansible.builtin.include_tasks: autofirma.yaml

- name: Include vscode tasks
  ansible.builtin.include_tasks: vscode.yaml

- name: Include endurance workaround for debian bug https://bugs.debian.org/991788
  become: true
  ansible.builtin.copy:
    src: systemd-sleep/manager.sh
    dest: /usr/lib/systemd/system-sleep/manager.sh
    owner: root
    group: root
    mode: "0755"
  when: ansible_facts['nodename'] == 'endurance'

- name: Include CHIRP tasks
  ansible.builtin.include_tasks: chirp.yaml
