---
- include_tasks: common.yml
- include_tasks: lightdm.yml
- include_tasks: profiler.yml
- include_tasks: spotify.yml
- include_tasks: signal.yaml
- ansible.builtin.include_tasks: slack.yaml

- name: Include telegram tasks
  ansible.builtin.include_tasks: telegram.yaml

- name: Include endurance workaround for debian bug https://bugs.debian.org/991788
  become: true
  ansible.builtin.copy:
    src: systemd-sleep/manager.sh
    dest: /usr/lib/systemd/system-sleep/manager.sh
    owner: root
    group: root
    mode: "0755"
  when: ansible_facts['nodename'] == 'endurance'
