---
- name: install spotify
  tags: desktop spotify
  become: true
  block:
    - name: spotify repository key
      ansible.builtin.get_url:
        url: https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg
        dest: /etc/apt/trusted.gpg.d/spotify.gpg

    - name: spotify repository source
      ansible.builtin.apt_repository:
        filename: spotify
        repo: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/spotify.gpg] http://repository.spotify.com stable non-free
        state: present

    - include_tasks: "{{ role_path }}/../common/tasks/apt-update-single-repository.yaml"
      vars:
        file: spotify.list

    - name: spotify package install
      apt:
        name: spotify-client
        state: latest
