---
# from https://www.spotify.com/us/download/linux/
- name: install spotify
  include_tasks: "{{ role_path }}/../common/tasks/apt-install-from-repository.yml"
  tags: desktop spotify
  vars:
    conf:
      shortname: spotify
      repo_spec: https://repository.spotify.com stable non-free
      key_url: https://download.spotify.com/debian/pubkey_C85668DF69375001.gpg
      packages:
        - spotify-client
