---
- name: install spotify
  include_tasks: "{{ role_path }}/../common/tasks/apt-install-from-repository.yml"
  tags: desktop spotify
  vars:
    conf:
      shortname: spotify
      repo_spec: http://repository.spotify.com stable non-free
      key_url: https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg
      packages:
        - spotify-client
