---
# see https://www.stremio.com/downloads
- name: Install stremio desktop
  become: true
  ansible.builtin.apt:
    deb: "https://dl.strem.io/shell-linux/v{{ version }}/stremio_{{ version }}-1_amd64.deb"
  vars:
    version: "4.4.168"
  register: result
  # don't fail if a later version has been installed
  failed_when: >
    result.failed == true and
    result.msg != "A later version is already installed"
