---
- name: Install vscode
  tags: vscode
  become: true
  ansible.builtin.apt:
    deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64

- name: Install vscode user settings file
  tags: rclone
  ansible.builtin.include_tasks: "{{ role_path }}/../dotfiles/tasks/link_dotfiles.yml"
  vars:
    dotfiles:
      - config/Code/User/settings.json

- name: Install vscode extensions
  ansible.builtin.command:
    cmd: code --install-extension "{{ item }}" --force
  # never changed, because otherwise is always changed
  changed_when: false
  loop:
    - golang.go
    - 4ops.terraform
    - redhat.vscode-yaml
