---
- name: Deploy xfce panel files
  ansible.builtin.copy:
    src: "config/xfce4/panel/"
    dest: "/home/{{ user }}/.config/xfc4/panel/"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"

- name: Configure xfce
  community.general.xfconf:
    channel: "{{ item.channel }}"
    property: "{{ item.property }}"
    value_type: "{{ item.type }}"
    value: "{{ item.value }}"
    force_array: "{{ item.force_array }}"
  loop: "{{ xfce_xfconf_data }}"
  loop_control:
    label: "{{ item.channel }} -> {{ item.property }}: {{ item.value }}"

- name: Deploy xfce autostartup files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/home/{{ user }}/.config/autostart/"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0755"
  with_fileglob:
    - "config/autostart/*"
