---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  TTLAfterFinished: true
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 30001
        hostPort: 30001
        protocol: TCP
    extraMounts:
      - hostPath: /data/project/
        containerPath: /data/project/
      - hostPath: /etc/wmcs-project
        containerPath: /etc/wmcs-project
      - hostPath: /var/lib/sss/pipes/
        containerPath: /var/lib/sss/pipes/
      - hostPath: /data/scratch
        containerPath: /data/scratch
      - hostPath: /public/dumps
        containerPath: /public/dumps
      - hostPath: /etc/ldap.conf
        containerPath: /etc/ldap.conf
      - hostPath: /etc/ldap.yaml
        containerPath: /etc/ldap.yaml
      - hostPath: /etc/novaobserver.yaml
        containerPath: /etc/novaobserver.yaml
      - hostPath: /mnt/nfs/dumps-clouddumps1001.wikimedia.org
        containerPath: /mnt/nfs/dumps-clouddumps1001.wikimedia.org
      - hostPath: /mnt/nfs/dumps-clouddumps1002.wikimedia.org
        containerPath: /mnt/nfs/dumps-clouddumps1002.wikimedia.org
