kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  "TTLAfterFinished": true
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 30001
    hostPort: 30001
    protocol: TCP
  extraMounts:
  - hostPath: /data/project/
    containerPath: /data/project/
  - hostPath: /etc/wmcs-project
    containerPath: /etc/wmcs-project
  - hostPath: /var/lib/sss/pipes/
    containerPath: /var/lib/sss/pipes/
