---
- name: Clone some public cg git repos (with gitsign)
  ansible.builtin.include_tasks: "{{ role_path }}/../git/tasks/clone.yml"
  vars:
    email: arturo.borrero@chainguard.dev
    configure_gitsign: true
    git_repos:
      - url: git@cg-github.com:wolfi-dev/os.git
        dir: cg/wolfi-dev/os
      - url: git@cg-github.com:wolfi-dev/advisories.git
        dir: cg/wolfi-dev/advisories
      - url: git@cg-github.com:aborrero/wolfi-dev_advisories.git
        dir: cg/wolfi-dev/advisories-fork
      - url: git@github.com:aborrero/wolfi-dev_os.git
        dir: cg/wolfi-dev/os-fork
      - url: git@cg-github.com:chainguard-dev/mono.git
        dir: cg/chainguard-dev/mono
      - url: git@cg-github.com:chainguard-dev/malcontent.git
        dir: cg/chainguard-dev/malcontent
      - url: git@cg-github.com:chainguard-dev/tw.git
        dir: cg/chainguard-dev/tw
      - url: git@cg-github.com:wolfi-dev/wolfictl.git
        dir: cg/wolfi-dev/wolfictl
      - url: git@cg-github.com:chainguard-images/images.git
        dir: cg/chainguard-images/images

- name: Clone some public cg git repos (no gitsign)
  ansible.builtin.include_tasks: "{{ role_path }}/../git/tasks/clone.yml"
  vars:
    email: arturo.borrero@chainguard.dev
    git_repos:
      - url: git@github.com:philroche/wolfi-package-status.git
        dir: cg/philroche/wolfi-package-status

- name: Install malcontent wrapper script
  become: true
  ansible.builtin.copy:
    src: malcontent.sh
    dest: /usr/local/bin/mal
    owner: root
    group: root
    mode: "0755"
