---
- name: ensure dotfiles required dirs exist
  tags: dotfiles
  become: true
  become_user: "{{user}}"
  ansible.builtin.file:
    dest: /home/{{user}}/.{{item|dirname}}
    state: directory
  loop: "{{dotfiles}}"

- name: backup previous dotfile
  include_tasks: "{{ role_path }}/../dotfiles/tasks/backup_previous_dotfile.yml"
  vars:
    reference: "{{item}}"
  loop: "{{dotfiles}}"

- name: create links for dotfiles
  tags: dotfiles
  become: true
  become_user: "{{user}}"
  ansible.builtin.file:
    src: "{{role_path}}/files/{{item}}"
    dest: /home/{{user}}/.{{item}}
    state: link
  loop: "{{dotfiles}}"
