---
- name: Deploy dotfiles
  ansible.builtin.include_tasks: link_dotfiles.yml
  vars:
    dotfiles:
      - bashrc
      - bash_aliases
      - config/liquidpromptrc
      - config/nano/nanorc
      - config/nano/puppet.nanorc
      - config/nano/yaml-template.nanorc
      - config/nano/hcl.nanorc
      - config/nano/dockerfile.nanorc
