---
- name: Clone gerritlab repository
  ansible.builtin.include_tasks: "{{ role_path }}/../git/tasks/clone.yml"
  vars:
    email: arturo.bg@arturo.bg
    git_repos:
      - url: https://github.com/yaoyuannnn/gerritlab
        dir: github/gerritlab

- name: Install gerritlab from upstream git repository via pipx
  community.general.pipx:
    name: gerritlab
    source: ~/git/github/gerritlab

- name: Install the gitlab CLI
  become: true
  ansible.builtin.apt:
    name: glab
    state: latest
