---
- name: Install custom WMF scripts
  tags: wmf
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /usr/local/bin/{{ item }}
    owner: root
    group: root
    mode: "0755"
  loop:
    - wmf-puppetserver-merge.sh
    - wmf-cleanup-puppetserver.sh
    - wmf-tools-merge.sh
    - wmf-export-puppet-patch.sh
    - wmf-git-review.sh
    - wmcs-update-known-hosts.sh

- name: Cleanup unused custom WMF scripts
  become: true
  ansible.builtin.file:
    path: "/usr/local/bin/{{ item }}"
    state: absent
  loop:
    - wmf-puppetmaster-merge.sh
    - wmf-cleanup-puppetmaster.sh

- name: Install wmf-laptop-sre
  ansible.builtin.include_tasks: "{{ role_path }}/../common/tasks/apt-install-from-repository.yml"
  tags: wmf
  vars:
    conf:
      shortname: wmf-laptop-sre
      repo_spec: http://apt.wikimedia.org/wikimedia buster-wikimedia component/wmf-sre-laptop
      key_url: https://wikitech.wikimedia.org/w/index.php?title=APT_repository/Stretch-Key&action=raw
      packages:
        - wmf-laptop-sre

- name: Clone some gerrit repos
  ansible.builtin.include_tasks: "{{ role_path }}/../git/tasks/clone.yml"
  vars:
    email: aborrero@wikimedia.org
    additional_commands:
      # make sure no push is done directly
      - "git remote set-url --push origin no_push_use_review"
    git_repos:
      - url: cumin1002.eqiad.wmnet:/srv/pwstore/pw.git
        dir: wmf/pw
      - url: ssh://aborrero@gerrit.wikimedia.org:29418/operations/puppet
        dir: wmf/operations/puppet
      - url: ssh://aborrero@gerrit.wikimedia.org:29418/operations/alerts
        dir: wmf/operations/alerts
      - url: ssh://aborrero@gerrit.wikimedia.org:29418/operations/dns
        dir: wmf/operations/dns
      - url: ssh://aborrero@gerrit.wikimedia.org:29418/operations/homer/public
        dir: wmf/operations/homer/public
      - url: ssh://gerrit.wikimedia.org:29418/cloud/instance-puppet
        dir: wmf/cloud/instance-puppet
      - url: ssh://gerrit.wikimedia.org:29418/cloud/instance-puppet-dev
        dir: wmf/cloud/instance-puppet-dev

- name: Clone some gitlab repos
  ansible.builtin.include_tasks: "{{ role_path }}/../git/tasks/clone.yml"
  vars:
    email: aborrero@wikimedia.org
    git_repos:
      - url: git@gitlab.wikimedia.org:repos/cloud/cicd/gitlab-ci.git
        dir: wmf/cloud/cicd/gitlab-ci
      - url: git@gitlab.wikimedia.org:repos/cloud/cloud-vps/tofu-infra.git
        dir: wmf/cloud/cloud-vps/tofu-infra
      - url: git@gitlab.wikimedia.org:repos/cloud/cloud-vps/designate-sink-wmcs-nova-fixed-ptr.git
        dir: wmf/cloud/cloud-vps/designate-sink-wmcs-nova-fixed-ptr

# another option (not in use in my setup as of today)
# * https://pypi.org/project/wm-ssh/
# * https://github.com/david-caro/wm-ssh
- name: Refresh ssh known hosts
  tags: ssh
  become: true
  become_user: "{{ user }}"
  ansible.builtin.shell: "{{ item }}"
  changed_when: false
  loop:
    - wmf-update-known-hosts-production /home/{{ user }}/git/wmf/operations/dns/
    - wmcs-update-known-hosts.sh

# see https://office.wikimedia.org/wiki/Pwstore
- name: Maintain pwstore configuration file
  ansible.builtin.copy:
    src: pws-trusted-users
    dest: /home/{{ user }}/.pws-trusted-users
    mode: "0644"

- name: Include spicerack tasks
  ansible.builtin.include_tasks: spicerack.yaml

- name: Include toolforge tasks
  ansible.builtin.include_tasks: toolforge.yaml

- name: Include prometheus tasks
  ansible.builtin.include_tasks: prometheus.yaml

- name: Include gerritlab tasks
  ansible.builtin.include_tasks: gerritlab.yaml

- name: Include opentofu tasks
  ansible.builtin.include_tasks: opentofu.yaml
