---
- name: Install opentofu
  ansible.builtin.include_tasks: "{{ role_path }}/../common/tasks/apt-install-from-repository.yml"
  vars:
    conf:
      shortname: "tofu"
      repo_spec: "https://packages.opentofu.org/opentofu/tofu/any/ any main"
      key_url: "https://packages.opentofu.org/opentofu/tofu/gpgkey"
      packages:
        - tofu
