---
- name: Clone spicerack/coobook git repos
  tags: spicerack
  ansible.builtin.include_tasks: "{{ role_path }}/../git/tasks/clone.yml"
  vars:
    email: aborrero@wikimedia.org
    git_repos:
      - url: ssh://aborrero@gerrit.wikimedia.org:29418/operations/cookbooks
        dir: wmf/operations/cookbooks
      - url: ssh://aborrero@gerrit.wikimedia.org:29418/cloud/wmcs-cookbooks
        dir: wmf/cloud/wmcs-cookbooks
      - url: ssh://aborrero@gerrit.wikimedia.org:29418/operations/software/spicerack
        dir: wmf/operations/software/spicerack
