---
- name: Clone Toolforge git repos
  tags: toolforge
  ansible.builtin.include_tasks: "{{ role_path }}/../git/tasks/clone.yml"
  vars:
    email: aborrero@wikimedia.org
    git_repos:
      - url: git@gitlab.wikimedia.org:repos/cloud/toolforge/tools-webservice.git
        dir: wmf/cloud/toolforge/tools-webservice
      - url: ssh://aborrero@gerrit.wikimedia.org:29418/operations/software/tools-manifest
        dir: wmf/operations/software/tools-manifest
      - url: git@gitlab.wikimedia.org:repos/cloud/toolforge/jobs-api
        dir: wmf/cloud/toolforge/jobs-api
      - url: git@gitlab.wikimedia.org:repos/cloud/toolforge/jobs-cli
        dir: wmf/cloud/toolforge/jobs-cli
      - url: git@gitlab.wikimedia.org:repos/cloud/toolforge/jobs-emailer
        dir: wmf/cloud/toolforge/jobs-emailer
      - url: ssh://gerrit.wikimedia.org:29418/cloud/toolforge/ingress-admission-controller
        dir: wmf/cloud/toolforge/ingress-admission-controller
      - url: git@gitlab.wikimedia.org:repos/cloud/toolforge/volume-admission-controller
        dir: wmf/cloud/toolforge/volume-admission-controller
      - url: git@gitlab.wikimedia.org:repos/cloud/toolforge/cert-manager
        dir: wmf/cloud/toolforge/cert-manager
      - url: git@gitlab.wikimedia.org:repos/cloud/toolforge/lima-kilo.git
        dir: wmf/cloud/toolforge/lima-kilo
      - url: git@gitlab.wikimedia.org:repos/cloud/toolforge/builds-admission-controller.git
        dir: wmf/cloud/toolforge/builds-admission-controller
      - url: ssh://aborrero@gerrit.wikimedia.org:29418/operations/docker-images/toollabs-images
        dir: wmf/operations/docker-images/toollabs-images
      - url: git@gitlab.wikimedia.org:repos/cloud/toolforge/calico.git
        dir: wmf/cloud/toolforge/calico
      - url: git@gitlab.wikimedia.org:repos/cloud/toolforge/image-config.git
        dir: wmf/cloud/toolforge/image-config
      - url: git@gitlab.wikimedia.org:repos/cloud/toolforge/api-gateway.git
        dir: wmf/cloud/toolforge/api-gateway
      - url: git@gitlab.wikimedia.org:repos/cloud/toolforge/foxtrot-ldap.git
        dir: wmf/cloud/toolforge/foxtrot-ldap
      - url: git@gitlab.wikimedia.org:repos/cloud/toolforge/toolforge-weld.git
        dir: wmf/cloud/toolforge/toolforge-weld
      - url: git@gitlab.wikimedia.org:repos/cloud/toolforge/toolforge-deploy.git
        dir: wmf/cloud/toolforge/toolforge-deploy
      - url: git@gitlab.wikimedia.org:repos/cloud/toolforge/envvars-api.git
        dir: wmf/cloud/toolforge/envvars-api
      - url: git@gitlab.wikimedia.org:repos/cloud/toolforge/builds-api.git
        dir: wmf/cloud/toolforge/builds-api
      - url: git@gitlab.wikimedia.org:repos/cloud/toolforge/builds-builder.git
        dir: wmf/cloud/toolforge/builds-builder
      - url: git@gitlab.wikimedia.org:repos/cloud/toolforge/builds-cli.git
        dir: wmf/cloud/toolforge/builds-cli
      - url: git@gitlab.wikimedia.org:repos/cloud/toolforge/maintain-kubeusers.git
        dir: wmf/cloud/toolforge/maintain-kubeusers

- name: Install toolforge lima-kilo userconfig file
  ansible.builtin.include_tasks: "{{ role_path }}/../dotfiles/tasks/link_dotfiles.yml"
  vars:
    dotfiles:
      - toolforge-lima-kilo/userconfig.yaml

# refresh version from https://github.com/lima-vm/lima/releases
- name: Install lima-vm
  ansible.builtin.include_tasks: "{{ role_path }}/../common/tasks/binary-install-from-url.yaml"
  vars:
    binary:
      name: "limactl"
      version: "0.20.1"
      version_command: "limactl --version"
      path: "/usr/local/bin/limactl"
      url: "https://github.com/lima-vm/lima/releases/download/v0.20.1/lima-0.20.1-Linux-x86_64.tar.gz"
      checksum: "sha256:e7093ca1889d2dab436d9f0e6b53d65336f75cf8ebd54f583085eca462a1fc4b"
      unpack: true

# from https://openapi-generator.tech
- name: Install openapi-generator from npm
  community.general.npm:
    name: "@openapitools/openapi-generator-cli"
    global: true
    state: present
