---
- name: Clone Toolforge git repos
  tags: toolforge
  ansible.builtin.include_tasks: "{{ role_path }}/../git/tasks/clone.yml"
  vars:
    email: aborrero@wikimedia.org
    git_repos:
      - url: git@gitlab.wikimedia.org:repos/cloud/toolforge/tools-webservice.git
        dir: wmf/cloud/toolforge/tools-webservice
      - url: ssh://aborrero@gerrit.wikimedia.org:29418/operations/software/tools-manifest
        dir: wmf/operations/software/tools-manifest
      - url: git@gitlab.wikimedia.org:repos/cloud/toolforge/jobs-api
        dir: wmf/cloud/toolforge/jobs-api
      - url: git@gitlab.wikimedia.org:repos/cloud/toolforge/jobs-cli
        dir: wmf/cloud/toolforge/jobs-cli
      - url: git@gitlab.wikimedia.org:repos/cloud/toolforge/jobs-emailer
        dir: wmf/cloud/toolforge/jobs-emailer
      - url: ssh://gerrit.wikimedia.org:29418/cloud/toolforge/ingress-admission-controller
        dir: wmf/cloud/toolforge/ingress-admission-controller
      - url: git@gitlab.wikimedia.org:repos/cloud/toolforge/volume-admission-controller
        dir: wmf/cloud/toolforge/volume-admission-controller
      - url: git@gitlab.wikimedia.org:repos/cloud/toolforge/cert-manager
        dir: wmf/cloud/toolforge/cert-manager
      - url: git@gitlab.wikimedia.org:repos/cloud/toolforge/lima-kilo.git
        dir: wmf/cloud/toolforge/lima-kilo
      - url: git@gitlab.wikimedia.org:repos/cloud/toolforge/builds-admission-controller.git
        dir: wmf/cloud/toolforge/builds-admission-controller
      - url: ssh://aborrero@gerrit.wikimedia.org:29418/operations/docker-images/toollabs-images
        dir: wmf/operations/docker-images/toollabs-images
      - url: git@gitlab.wikimedia.org:repos/cloud/toolforge/calico.git
        dir: wmf/cloud/toolforge/calico
      - url: git@gitlab.wikimedia.org:repos/cloud/toolforge/image-config.git
        dir: wmf/cloud/toolforge/image-config
      - url: git@gitlab.wikimedia.org:repos/cloud/toolforge/api-gateway.git
        dir: wmf/cloud/toolforge/api-gateway
      - url: git@gitlab.wikimedia.org:repos/cloud/toolforge/foxtrot-ldap.git
        dir: wmf/cloud/toolforge/foxtrot-ldap
      - url: git@gitlab.wikimedia.org:repos/cloud/toolforge/toolforge-weld.git
        dir: wmf/cloud/toolforge/toolforge-weld
      - url: git@gitlab.wikimedia.org:repos/cloud/toolforge/toolforge-deploy.git
        dir: wmf/cloud/toolforge/toolforge-deploy
      - url: git@gitlab.wikimedia.org:repos/cloud/toolforge/envvars-api.git
        dir: wmf/cloud/toolforge/envvars-api
      - url: git@gitlab.wikimedia.org:repos/cloud/toolforge/builds-api.git
        dir: wmf/cloud/toolforge/builds-api
      - url: git@gitlab.wikimedia.org:repos/cloud/toolforge/builds-builder.git
        dir: wmf/cloud/toolforge/builds-builder
      - url: git@gitlab.wikimedia.org:repos/cloud/toolforge/builds-cli.git
        dir: wmf/cloud/toolforge/builds-cli
      - url: git@gitlab.wikimedia.org:repos/cloud/toolforge/maintain-kubeusers.git
        dir: wmf/cloud/toolforge/maintain-kubeusers

- name: Install toolforge lima-kilo userconfig file
  ansible.builtin.include_tasks: "{{ role_path }}/../dotfiles/tasks/link_dotfiles.yml"
  vars:
    dotfiles:
      - toolforge-lima-kilo/userconfig.yaml

- name: Install fake toolforge-jobs
  tags: toolforge
  become: true
  ansible.builtin.copy:  # noqa template-instead-of-copy
    content: |
      #!/bin/bash
      source ~/.pyvenvs/jobs-framework-cli/bin/activate
      ~/.toolforge-lima-kilo/bin/toolforge-jobs "$@"
    dest: /usr/local/bin/toolforge-jobs
    mode: "0755"

- name: Install fake toolforge-build
  tags: toolforge
  become: true
  ansible.builtin.copy:  # noqa template-instead-of-copy
    content: |
      #!/bin/bash
      source ~/.pyvenvs/builds-cli/bin/activate
      ~/.toolforge-lima-kilo/bin/toolforge-build "$@"
    dest: /usr/local/bin/toolforge-build
    mode: "0755"
