---
- name: Create dput profile dir
  ansible.builtin.file:
    path: /home/{{ user }}/.dput.d/profiles/
    state: directory
    mode: '0755'
    recurse: true

- name: Install dput default config
  ansible.builtin.copy:
    dest: /home/{{ user }}/.dput.d/profiles/DEFAULT.json
    mode: "0644"
    content: |
      {
          "default_keyid": "DD9861AB23DC3333892E07A968E713981D1515F8"
      }
