---
- name: install debian devel packages
  tags: cli debian
  become: true
  apt:
    name: "{{ package }}"
    state: latest
  vars:
    package:
      - debmake
      - sbuild
      - schroot
      - git-buildpackage
      - pristine-tar
      - apt-cacher-ng
      - mmdebstrap

- name: install some debian-related dotfiles
  include_tasks: "{{ role_path }}/../dotfiles/tasks/link_dotfiles.yml"
  vars:
    dotfiles:
      - reportbugrc
      - sbuildrc

- name: Add user to sbuild Unix group
  become: true
  ansible.builtin.user:
    name: "{{ user }}"
    groups: sbuild
    append: true

- name: sbuild chroot setup
  include_tasks: "{{ role_path }}/../debian/tasks/sbuild.yml"
  vars:
    distributions:
      - unstable
      # for toolforge servers
      - buster

- name: clone some git repos
  include_tasks: "{{ role_path }}/../git/tasks/clone.yml"
  vars:
    email: arturo@debian.org
    git_repos:
      - url: git@salsa.debian.org:pkg-netfilter-team/pkg-nftables.git
        dir: debian/nftables/pkg-nftables
      - url: git@salsa.debian.org:pkg-netfilter-team/pkg-libnftnl.git
        dir: debian/libnftnl/pkg-libnftnl
      - url: git@salsa.debian.org:pkg-netfilter-team/pkg-iptables.git
        dir: debian/iptables/pkg-iptables
      - url: git@salsa.debian.org:pkg-netfilter-team/pkg-arptables.git
        dir: debian/arptables/pkg-arptables
      - url: git@salsa.debian.org:pkg-netfilter-team/pkg-ebtables.git
        dir: debian/ebtables/pkg-ebtables
      - url: git@salsa.debian.org:pkg-netfilter-team/pkg-nftlb.git
        dir: debian/nftlb/pkg-nftlb
      - url: git@salsa.debian.org:pkg-netfilter-team/pkg-libmnl.git
        dir: debian/libmnl/pkg-libmnl
      - url: git@salsa.debian.org:pkg-netfilter-team/pkg-conntrack-tools.git
        dir: debian/conntrack-tools/pkg-conntrack-tools
      - url: git@salsa.debian.org:pkg-netfilter-team/pkg-xtables-addons.git
        dir: debian/xtables-addons/pkg-xtables-addons
      - url: git@salsa.debian.org:pkg-netfilter-team/pkg-libnetfilter-conntrack.git
        dir: debian/libnetfilter-conntrack/pkg-libnetfilter-conntrack
      - url: git@salsa.debian.org:pkg-netfilter-team/pkg-libnetfilter-cthelper.git
        dir: debian/libnetfilter-cthelper/pkg-libnetfilter-cthelper
      - url: git@salsa.debian.org:pkg-netfilter-team/pkg-libnetfilter-cttimeout.git
        dir: debian/libnetfilter-cttimeout/pkg-libnetfilter-cttimeout
      - url: git@salsa.debian.org:pkg-netfilter-team/pkg-libnetfilter-log.git
        dir: debian/libnetfilter-log/pkg-libnetfilter-log
      - url: git@salsa.debian.org:pkg-netfilter-team/pkg-libnetfilter-queue.git
        dir: debian/libnetfilter-queue/pkg-libnetfilter-queue
      - url: git@salsa.debian.org:debian/pkg-capirca.git
        dir: debian/capirca/pkg-capirca
      - url: git@salsa.debian.org:debian/pkg-liquidprompt.git
        dir: debian/liquidprompt/pkg-liquidprompt
