---
# target_config:
#   mirror: string
#   release: string

- name: "Create chroot for {{ release }}"
  vars:
    sbuild_create: /usr/bin/sbuild-createchroot
    sbuild_create_opts: --include=eatmydata,ccache,lintian --debootstrap=mmdebstrap
    sbuild_mirror: "http://127.0.0.1:3142/{{ target_config.mirror | default('deb.debian.org/debian') }}"
    basedir: /srv/chroot
    release: "{{ target_config.release }}"
  become: true
  ansible.builtin.command:
    cmd: "{{ sbuild_create }} {{ sbuild_create_opts }} {{ release }} {{ basedir }}/{{ release }}-amd64-sbuild {{ sbuild_mirror }}"
    creates: /etc/sbuild/chroot/{{ release }}-amd64-sbuild

- name: "Update chroot for {{ release }}"
  become: true
  vars:
    sbuild_update: /usr/bin/sbuild-update -udcar
    release: "{{target_config.release}}"
  ansible.builtin.command:
    cmd: "{{ sbuild_update }} {{ release }}-amd64-sbuild"
  # never changed, because otherwise is always changed
  changed_when: false
