---
- name: Install docker
  ansible.builtin.include_tasks: "{{ role_path }}/../common/tasks/apt-install-from-repository.yml"
  tags: docker
  vars:
    conf:
      shortname: docker
      # they don't have bookworm yet https://download.docker.com/linux/debian/dists/
      repo_spec: https://download.docker.com/linux/debian bullseye stable
      key_url: https://download.docker.com/linux/debian/gpg
      packages:
        - docker-ce
        - docker-ce-cli
        - containerd.io

- name: Install docker compose
  tags: docker
  become: true
  ansible.builtin.apt:
    name: docker-compose
    state: latest

- name: Manage docker group membership
  tags: docker
  become: true
  ansible.builtin.user:
    name: "{{ user }}"
    groups: docker
    append: true

- name: Create docker data root
  tags: docker
  become: true
  ansible.builtin.file:
    # noqa: risky-file-permissions
    dest: "{{ docker.data_root }}"
    state: directory

- name: Docker daemon configuration directory
  tags: docker
  become: true
  ansible.builtin.file:
    # noqa: risky-file-permissions
    dest: /etc/docker
    state: directory

- name: Install docker daemon configuration
  tags: docker
  become: true
  ansible.builtin.template:
    src: docker/daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: "0644"
  notify: "Restart docker daemon"
