---
- name: install docker
  include_tasks: "{{ role_path }}/../common/tasks/apt-install-from-repository.yml"
  tags: k8s docker
  vars:
    conf:
      shortname: docker
      # they don't have bookworm yet https://download.docker.com/linux/debian/dists/
      repo_spec: https://download.docker.com/linux/debian bullseye stable
      key_url: https://download.docker.com/linux/debian/gpg
      packages:
        - docker-ce
        - docker-ce-cli
        - containerd.io

- name: docker group membership
  become: true
  ansible.builtin.user:
    name: "{{user}}"
    groups: docker
    append: true

- name: docker data root
  become: true
  ansible.builtin.file:
    dest: /home/{{user}}/.docker
    state: directory

- name: docker data root permissions
  become: true
  ansible.builtin.shell: chown "{{user}}":"{{user}}" "/home/{{user}}/.docker" -R
  changed_when: false

- name: docker daemon configuration directory
  become: true
  ansible.builtin.file:
    dest: /etc/docker
    state: directory

- name: docker daemon configuration
  become: true
  ansible.builtin.copy:
    src: docker/daemon.json
    dest: /etc/docker/daemon.json
  register: dockerconfig

- name: restart docker daemon if config changed
  become: true
  ansible.builtin.systemd:
    name: docker.service
    state: restarted
  when: dockerconfig.changed
