---
- name: install docker
  tags: k8s docker
  become: true
  block:
    - name: docker repository key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/trusted.gpg.d/docker.asc

    - name: docker repository source
      ansible.builtin.apt_repository:
        # they don't have bookworm yet https://download.docker.com/linux/debian/dists/
        repo: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/debian bullseye stable
        state: present
        filename: docker

    - include_tasks: "{{ role_path }}/../common/tasks/apt-update-single-repository.yaml"
      vars:
        file: docker.list

    - name: docker packages are installed
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest

- name: docker group membership
  become: true
  ansible.builtin.user:
    name: "{{user}}"
    groups: docker
    append: true

- name: docker data root
  become: true
  ansible.builtin.file:
    dest: "/home/{{user}}/.docker"
    state: directory

- name: docker data root permissions
  become: true
  ansible.builtin.shell: chown "{{user}}":"{{user}}" "/home/{{user}}/.docker" -R

- name: docker daemon configuration directory
  become: true
  ansible.builtin.file:
    dest: /etc/docker
    state: directory

- name: docker daemon configuration
  become: true
  ansible.builtin.copy:
    src: docker/daemon.json
    dest: /etc/docker/daemon.json
  register: dockerconfig

- name: restart docker daemon if config changed
  become: true
  ansible.builtin.systemd:
    name: docker.service
    state: restarted
  when: dockerconfig.changed
