- name: install helm repository
  tags:
    k8s
    helm
  block:
    - name: helm repository key
      ansible.builtin.get_url:
        url: https://baltocdn.com/helm/signing.asc
        dest: /etc/apt/trusted.gpg.d/helm.asc

    - name: helm repository source
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/helm.asc] https://baltocdn.com/helm/stable/debian/ all main"
        state: present

    - name: helm repository is available
      apt:
        name: helm
        state: latest
        update_cache: yes
