---
- name: install helm
  include_tasks: "{{ role_path }}/../common/tasks/apt-install-from-repository.yml"
  tags: k8s helm
  vars:
    conf:
      shortname: helm
      repo_spec: https://baltocdn.com/helm/stable/debian/ all main
      key_url: https://baltocdn.com/helm/signing.asc
      packages:
        - helm

- name: install helm cm-push plugin
  tags: k8s helm
  become: true
  become_user: "{{user}}"
  ansible.builtin.shell: helm plugin install https://github.com/chartmuseum/helm-push || true
  register: result
  changed_when: "'Error: plugin already exists' not in result.stderr"
