---
- name: Install helm cm-push plugin
  tags: helm
  become: true
  become_user: "{{ user }}"
  ansible.builtin.shell: helm plugin install https://github.com/chartmuseum/helm-push || true
  register: result
  changed_when: "'Error: plugin already exists' not in result.stderr"
