- name: verify if kind is installed
  tags:
    k8s
    kind
  become: no
  ansible.builtin.stat:
    path: /usr/local/bin/kind
  register: filecheck

- name: verify kind version
  tags:
    k8s
    kind
  become: no
  ansible.builtin.shell: kind --version
  register: kindversion

- name: download kind
  tags:
    k8s
    kind
  become: no
  # refresh versions from https://github.com/kubernetes-sigs/kind/releases
  ansible.builtin.get_url:
    url: https://kind.sigs.k8s.io/dl/v0.17.0/kind-linux-amd64
    dest: /tmp/ansible_download_kind
    checksum: sha256:a8c045856db33f839908b6acb90dc8ec397253ffdaef7baf058f5a542e009b9c
  when: filecheck.stat.executable == False or kindversion.stdout != "kind version 0.17.0"
  register: kind_download

- name: install kind
  tags:
    k8s
    kind
  ansible.builtin.copy:
    src: /tmp/ansible_download_kind
    dest: /usr/local/bin/kind
    mode: '0755'
  when: kind_download

- name: install kind configuration dotfile
  include_tasks: "{{ role_path }}/../dotfiles/tasks/link_dotfiles.yml"
  vars:
    dotfiles:
      - kind.yaml

