---
- include_tasks: docker.yml
- include_tasks: kind.yml
- include_tasks: helm.yml

- name: install podman
  become: true
  ansible.builtin.apt:
    name: podman
    state: latest

- name: install kubectl
  include_tasks: "{{ role_path }}/../common/tasks/apt-install-from-repository.yml"
  tags: k8s kubectl
  vars:
    conf:
      shortname: kubectl
      repo_spec: https://apt.kubernetes.io/ kubernetes-xenial main
      key_url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      packages:
        - kubectl
