---
- name: Include docker tasks
  ansible.builtin.include_tasks: docker.yml

- name: Include helm tasks
  ansible.builtin.include_tasks: helm.yml

- name: Install k8s-related packages
  tags: apt
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      # this conflicts with some toolforge components
      # - podman
      - python3-kubernetes
      - jq
      # for k9s to be able to copy logs from the ui
      - xsel

# see https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-using-native-package-management
- name: Install kubectl
  include_tasks: "{{ role_path }}/../common/tasks/apt-install-from-repository.yml"
  vars:
    conf:
      shortname: kubectl
      repo_spec: https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /
      key_url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
      packages:
        - kubectl

- name: Install binaries from URLs
  tags: k8s
  ansible.builtin.include_tasks: "{{ role_path }}/../common/tasks/binary-install-from-url.yaml"
  loop: "{{ k8s_binary_install_from_url }}"
  loop_control:
    loop_var: binary
    label: "{{ binary.name }}"

- name: Install some k8s dotfiles
  ansible.builtin.include_tasks: "{{ role_path }}/../dotfiles/tasks/link_dotfiles.yml"
  vars:
    dotfiles:
      - config/k9s/config.yaml
      - config/k9s/hotkeys.yaml
      - config/k9s/aliases.yaml
      - config/k9s/skins/everforest-dark.yaml
      - config/k9s/skins/kanagawa.yaml

- name: Git clone k8s repos
  ansible.builtin.include_tasks: "{{ role_path }}/../git/tasks/clone.yml"
  vars:
    email: arturo.bg@arturo.bg
    git_repos:
      - url: https://github.com/kubernetes-sigs/contributor-playground
        dir: k8s-sigs/contributor-playground

