---
- name: Include docker tasks
  ansible.builtin.include_tasks: docker.yml

- name: Include kind tasks
  ansible.builtin.include_tasks: kind.yml

- name: Include helm tasks
  ansible.builtin.include_tasks: helm.yml

- name: Install k8s-related packages
  tags: apt
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - podman
      - python3-kubernetes
      - jq
