---
- include_tasks: docker.yml
- include_tasks: kind.yml
- include_tasks: helm.yml

- name: Install k8s-related packages
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - podman
      - python3-kubernetes
      - jq
