export LS_OPTIONS='--color=auto'
eval "$(dircolors)"
alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -l'
alias treel='tree -L 2 --filesfirst -F'

alias grep='grep --color'

alias sudo='sudo '
alias tailf='tail -f'

alias gldoc='git log --decorate --oneline --color'
alias gll='git log --pretty=format:"%C(yellow)%h %Creset%s%Cblue [%ae] (%ad)" --decorate --numstat --date=relative --shortstat'
alias grpo='git remote prune origin'

# this is now a script
#alias gry='git review -y'

# Comment for now. Podman tags local images as localhost/<image>:latest
# and plenty of my kubernetes manifests can't work with that
#alias docker='podman'

# spryker
alias sdk='/home/arturo/git/spryker/docker-sdk/sdk'
