export LS_OPTIONS='--color=auto'
eval "$(dircolors)"
alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -l'
alias treel='tree -L 2 --filesfirst -F'
alias diff='diff -u --color'

alias grep='grep --color'

alias sudo='sudo '
alias tailf='tail -f'

alias gldoc='git log --decorate --oneline --color'
alias gll='git log --pretty=format:"%C(yellow)%h %Creset%s%Cblue [%ae] (%ad)" --decorate --numstat --date=relative --shortstat'
alias grpo='git remote prune origin'

# this is now a script
#alias gry='git review -y'

# Comment for now. Podman tags local images as localhost/<image>:latest
# and plenty of my kubernetes manifests can't work with that
#alias docker='podman'

# fuzzy grep search
# this shows all files in a fzf preview panel with grep search context
fgs() {
    if [ "$1" == "" ] ; then
        return 1
    fi

    grep --ignore-case --recursive --files-with-matches --only-matching --binary-files=without-match --no-messages "$1" * \
        | fzf --preview "grep --ignore-case --color=always --context 3 '$1' {}"
}

# fuzzy git grep search
fggs () {
    if [ "$1" == "" ] ; then
        return 1
    fi

    git grep --ignore-case --no-index -I --full-name --files-with-matches "$1" \
        | fzf --preview "git grep --ignore-case --color=always --context 3 '$1' {}"
}

# fuzzy file browser
alias ffb='fzf --preview "pygmentize -g {}"'
