---
- name: Install python3 packages
  tags: apt
  become: true
  ansible.builtin.apt:
    pkg:
      - python3-pip
      - python3-dev
      - python3-venv
      - python3-poetry
      - tox
      - isort
      - pipx
    state: latest

- name: Install some utilities via pipx
  community.general.pipx:
    name: "{{ item }}"
  loop:
    - ruff
    - openapi-python-client
    # https://github.com/Textualize/toolong
    - toolong
