---
- name: Install python3 packages
  tags: apt
  become: true
  ansible.builtin.apt:
    pkg:
      - python3-pip
      - python3-dev
      - python3-venv
      - tox
      - isort
      - pipx
    state: latest

- name: Install some utilities via pipx
  community.general.pipx:
    name: "{{ item }}"
  loop:
    - ruff
    - openapi-python-client
    # https://github.com/Textualize/toolong
    - toolong

- name: Create virtualenvs directory
  become: true
  become_user: "{{ user }}"
  ansible.builtin.file:
    # noqa: risky-file-permissions
    dest: /home/{{ user }}/.pyvenvs/
    state: directory

# TODO: no venvs at the moment!
#
#- name: Create virtualenvs
#  tags: pyvenv
#  become: true
#  become_user: "{{ user }}"
#  ansible.builtin.command:
#    cmd: python3 -m venv /home/{{ user }}/.pyvenvs/{{ item }}
#    creates: /home/{{ user }}/.pyvenvs/{{ item }}/bin/activate
#  loop:
#    - <nothing>
