---
- name: install python3 packages
  become: true
  ansible.builtin.apt:
    pkg:
      - python3-pip
      - python3-dev
      - python3-venv
    state: latest

- name: virtualenvs directory
  become: true
  become_user: "{{user}}"
  ansible.builtin.file:
    dest: /home/{{user}}/.pyvenvs/
    state: directory

- name: create virtualenvs
  become: true
  become_user: "{{user}}"
  ansible.builtin.command:
    cmd: python3 -m venv /home/{{user}}/.pyvenvs/{{item}}
    creates: /home/{{user}}/.pyvenvs/{{item}}/bin/activate
  loop:
    - jobs-framework-api
    - jobs-framework-cli
    - jobs-framework-emailer
    - tools-webservice
    - spicerack
