---
- name: Install libvirt packages
  tags: libvirt
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - qemu-system
      - libvirt-daemon-system
      - virt-manager
      - bridge-utils

- name: Add user to libvirt Unix group
  become: true
  ansible.builtin.user:
    name: '{{ user }}'
    groups: libvirt
    append: yes
