---
- name: Install libvirt packages
  tags: apt
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - qemu-system
      - libvirt-daemon-system
      - virt-manager
      - bridge-utils
      - guestfs-tools
      # to use the community.libvirt module below
      - python3-lxml

- name: Add user to libvirt Unix group
  become: true
  ansible.builtin.user:
    name: "{{ user }}"
    groups: libvirt
    append: true

- name: Create directory tree for default storage pool
  become: true
  become_user: "{{ user }}"
  ansible.builtin.file:
    # noqa: risky-file-permissions
    path: /home/{{ user }}/.local/share/libvirt/images/
    state: directory

- name: Define default storage pool pointing to /home
  tags: libvirt
  community.libvirt.virt_pool:
    command: define
    name: default
    xml: '{{ lookup("template", "default-storage-pool.xml.j2") }}'

- name: Set up default storage pool
  tags: libvirt
  community.libvirt.virt_pool:
    command: "{{ item }}"
    name: defaults
  loop:
    - build
    - create
    - start
  register: result
  failed_when:
    - result.rc is defined and result.rc != 0
    - '"is already active" not in result.msg'
