---
- name: Install ssh packages
  tags: ssh
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - openssh-client
      - openssh-server

- name: Install ssh config dotfile
  ansible.builtin.include_tasks: "{{ role_path }}/../dotfiles/tasks/link_dotfiles.yml"
  vars:
    dotfiles:
      - ssh/config

#- name: Import systemd ssh agent tasks
#  ansible.builtin.import_tasks: systemd_ssh_agent.yml
#  vars:
#    names:
#      - ssh-personal
