- name: install ssh packages
  tags: ssh
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - openssh-client
    - openssh-server

- name: install ~/.ssh/config
  tags: ssh
  copy: src=client_ssh_config dest=/home/{{user}}/.ssh/config

- import_tasks:  systemd_ssh_agent.yml
  vars:
    names:
      - ssh-wmf-cloud-root
      - ssh-wmf-cloud-user
      - ssh-wmf-gerrit
      - ssh-wmf-prod
