---
- name: Run systemd daemon reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart nftables service
  become: true
  ansible.builtin.systemd:
    name: nftables.service
    state: restarted
