---
# see https://docs.ansible.com/ansible/latest/collections/community/general/xfconf_module.html
# and https://forum.xfce.org/viewtopic.php?pid=32033#p32033
xfce_xfconf_data:
  # workspaces
  - channel: "xfwm4"
    property: "/general/workspace_count"
    type: "int"
    value: "2"
    force_array: false

  - channel: "xfwm4"
    property: "/general/workspace_names"
    type: "string"
    value: ['main', 'secondary']
    force_array: true

  # behavior
  - channel: "xfwm4"
    property: "/general/click_to_focus"
    type: "bool"
    value: "false"
    force_array: false

  # disable mouse wheel to roll up windows
  - channel: "xfwm4"
    property: "/general/mousewheel_rollup"
    type: "bool"
    value: "false"
    force_array: false

  # aspect
  - channel: "xsettings"
    property: "/Net/ThemeName"
    type: "string"
    value: "Adwaita-dark"
    force_array: false

  # main panel, main app button
  - channel: "xfce4-panel"
    property: "/plugins/plugin-1/show-button-title"
    type: "bool"
    value: "false"
    force_array: false

  # main panel, show in main display
  - channel: "xfce4-panel"
    property: "/panels/panel-1/output-name"
    type: "string"
    value: "Primary"
    force_array: false

  # lower panel, show in main display
  - channel: "xfce4-panel"
    property: "/panels/panel-2/output-name"
    type: "string"
    value: "Primary"
    force_array: false

  # lower panel, auto hide
  - channel: "xfce4-panel"
    property: "/panels/panel-2/autohide-behavior"
    type: "int"
    value: "2"
    force_array: false

  # lower panel, show desktop button
  - channel: "xfce4-panel"
    property: "/plugins/plugin-15"
    type: "string"
    value: "showdesktop"
    force_array: false

  # lower panel, separator
  - channel: "xfce4-panel"
    property: "/plugins/plugin-16"
    type: "string"
    value: "separator"
    force_array: false

  # lower panel, launcher for terminal
  - channel: "xfce4-panel"
    property: "/plugins/plugin-17"
    type: "string"
    value: "launcher"
    force_array: false

  # lower panel, launcher for terminal
  - channel: "xfce4-panel"
    property: "/plugins/plugin-17/items"
    type: "string"
    value: ["17126586841.desktop"]
    force_array: true

  # lower panel, launcher for file manager
  - channel: "xfce4-panel"
    property: "/plugins/plugin-18"
    type: "string"
    value: "launcher"
    force_array: false

  # lower panel, launcher for file manager
  - channel: "xfce4-panel"
    property: "/plugins/plugin-18/items"
    type: "string"
    value: ["17126586842.desktop"]
    force_array: true

  # lower panel, launcher for chrome browser
  - channel: "xfce4-panel"
    property: "/plugins/plugin-19"
    type: "string"
    value: "launcher"
    force_array: false

  # lower panel, launcher for chrome browser
  - channel: "xfce4-panel"
    property: "/plugins/plugin-19/items"
    type: "string"
    value: ["17126586853.desktop"]
    force_array: true

  # lower panel, launcher for screenshooter
  - channel: "xfce4-panel"
    property: "/plugins/plugin-21"
    type: "string"
    value: "screenshooter"
    force_array: false

  # lower panel, launcher for firefox browser
  - channel: "xfce4-panel"
    property: "/plugins/plugin-13"
    type: "string"
    value: "launcher"
    force_array: false

  # lower panel, launcher for firefox browser
  - channel: "xfce4-panel"
    property: "/plugins/plugin-13/items"
    type: "string"
    value: ["17576746301.desktop"]
    force_array: true

  # lower panel, setting
  - channel: "xfce4-panel"
    property: "/panels/panel-2/plugin-ids"
    type: "int"
    value: ['15', '16', '17', '18', '19', '21', '13']
    force_array: true

  # action buttons for shutdown/etc
  - channel: "xfce4-panel"
    property: "/plugins/plugin-14/button-title"
    type: "int"
    value: "1"
    force_array: false

  # mouse, touchpad
  - channel: "pointers"
    property: "/SynPS2_Synaptics_TouchPad/Acceleration"
    type: "double"
    value: "8.000000"
    force_array: false

  # background, left HDMI monitor if connected directly
  - channel: "xfce4-desktop"
    property: "/backdrop/screen0/monitorDP-1-2/workspace0/last-image"
    type: "string"
    value: "/usr/share/backgrounds/green_mountain_vertical.jpeg"
    force_array: false

  # background, main HDMI monitor if connected directly
  - channel: "xfce4-desktop"
    property: "/backdrop/screen0/monitorHDMI-1-0/workspace0/last-image"
    type: "string"
    value: "/usr/share/backgrounds/green_valey.jpg"
    force_array: false

  # background, laptop screen
  - channel: "xfce4-desktop"
    property: "/backdrop/screen0/monitoreDP-1/workspace0/last-image"
    type: "string"
    value: "/usr/share/backgrounds/blue_mountains.jpg"
    force_array: false

  # background, left HDMI monitor if connected via docking station
  - channel: "xfce4-desktop"
    property: "/backdrop/screen0/monitorDVI-I-3-2/workspace0/last-image"
    type: "string"
    value: "/usr/share/backgrounds/green_mountain_vertical.jpeg"
    force_array: false

  # background, main HDMI monitor if connected via docking station
  - channel: "xfce4-desktop"
    property: "/backdrop/screen0/monitorDVI-I-2-1/workspace0/last-image"
    type: "string"
    value: "/usr/share/backgrounds/green_valey.jpg"
    force_array: false

  # mechanical keyboard bounce keys settings to prevent keyboard chattering
  - channel: "accessibility"
    property: "/BounceKeys"
    type: "bool"
    value: "true"
    force_array: false

  # mechanical keyboard bounce keys settings to prevent keyboard chattering
  - channel: "accessibility"
    property: "/BounceKeys/Delay"
    type: "int"
    value: "50"
    force_array: false
