---
# see https://docs.ansible.com/ansible/latest/collections/community/general/xfconf_module.html
# and https://forum.xfce.org/viewtopic.php?pid=32033#p32033
xfce_xfconf_data:
  # workspaces
  - channel: "xfwm4"
    property: "/general/workspace_count"
    type: "int"
    value: "2"
    force_array: false

  - channel: "xfwm4"
    property: "/general/workspace_names"
    type: "string"
    value: ['main', 'secondary']
    force_array: true

  # behavior
  - channel: "xfwm4"
    property: "/general/click_to_focus"
    type: "bool"
    value: "false"
    force_array: false

  # aspect
  - channel: "xsettings"
    property: "/Net/ThemeName"
    type: "string"
    value: "Adwaita-dark"
    force_array: false

  # main panel, main app button
  - channel: "xfce4-panel"
    property: "/plugins/plugin-1/show-button-title"
    type: "bool"
    value: "false"
    force_array: false

  # main panel, show in main display
  - channel: "xfce4-panel"
    property: "/panels/panel-1/output-name"
    type: "string"
    value: "Primary"
    force_array: false

  # lower panel, show in main display
  - channel: "xfce4-panel"
    property: "/panels/panel-2/output-name"
    type: "string"
    value: "Primary"
    force_array: false

  # lower panel, auto hide
  - channel: "xfce4-panel"
    property: "/panels/panel-2/autohide-behavior"
    type: "int"
    value: "2"
    force_array: false

  # lower panel, show desktop button
  - channel: "xfce4-panel"
    property: "/plugins/plugin-15"
    type: "string"
    value: "showdesktop"
    force_array: false

  # lower panel, separator
  - channel: "xfce4-panel"
    property: "/plugins/plugin-16"
    type: "string"
    value: "separator"
    force_array: false

  # lower panel, launcher for terminal
  - channel: "xfce4-panel"
    property: "/plugins/plugin-17"
    type: "string"
    value: "launcher"
    force_array: false

  # lower panel, launcher for terminal
  - channel: "xfce4-panel"
    property: "/plugins/plugin-17/items"
    type: "string"
    value: ["17126586841.desktop"]
    force_array: true

  # lower panel, launcher for file manager
  - channel: "xfce4-panel"
    property: "/plugins/plugin-18"
    type: "string"
    value: "launcher"
    force_array: false

  # lower panel, launcher for file manager
  - channel: "xfce4-panel"
    property: "/plugins/plugin-18/items"
    type: "string"
    value: ["17126586842.desktop"]
    force_array: true

  # lower panel, launcher for firefox
  - channel: "xfce4-panel"
    property: "/plugins/plugin-19"
    type: "string"
    value: "launcher"
    force_array: false

  # lower panel, launcher for firefox
  - channel: "xfce4-panel"
    property: "/plugins/plugin-19/items"
    type: "string"
    value: ["17126586853.desktop"]
    force_array: true

  # lower panel, launcher for screenshooter
  - channel: "xfce4-panel"
    property: "/plugins/plugin-21"
    type: "string"
    value: "screenshooter"
    force_array: false

  # lower panel, setting
  - channel: "xfce4-panel"
    property: "/panels/panel-2/plugin-ids"
    type: "int"
    value: ['15', '16', '17', '18', '19', '21']
    force_array: true

  # action buttons for shutdown/etc
  - channel: "xfce4-panel"
    property: "/plugins/plugin-14/button-title"
    type: "int"
    value: "1"
    force_array: false

  # mouse, touchpad
  - channel: "pointers"
    property: "/SynPS2_Synaptics_TouchPad/Acceleration"
    type: "double"
    value: "8.000000"
    force_array: false

  # background, left HDMI monitor
  - channel: "xfce4-desktop"
    property: "/backdrop/screen0/monitorDP-1-2/workspace0/last-image"
    type: "string"
    value: "/usr/share/backgrounds/green_mountain_vertical.jpeg"
    force_array: false

  # background, main HDMI monitor
  - channel: "xfce4-desktop"
    property: "/backdrop/screen0/monitorHDMI-1-0/workspace0/last-image"
    type: "string"
    value: "/usr/share/backgrounds/green_valey.jpg"
    force_array: false

  # background, laptop screen
  - channel: "xfce4-desktop"
    property: "/backdrop/screen0/monitoreDP-1/workspace0/last-image"
    type: "string"
    value: "/usr/share/backgrounds/blue_mountains.jpg"
    force_array: false

  # display settings, default settings
  - channel: displays
    force_array: 'false'
    property: /ActiveProfile
    type: string
    value: d4df945a4760356ad978ade7ffc60a03c3acbb12

  - channel: displays
    force_array: 'false'
    property: /Default/DP-1-2
    type: string
    value: ASUS 27"

  - channel: displays
    force_array: 'false'
    property: /Default/DP-1-2/Active
    type: bool
    value: 'true'

  - channel: displays
    force_array: 'false'
    property: /Default/DP-1-2/EDID
    type: string
    value: 71f8026b5cdd2776c54bd1529eb350fd35526c9e

  - channel: displays
    force_array: 'false'
    property: /Default/DP-1-2/Position/X
    type: int
    value: '0'

  - channel: displays
    force_array: 'false'
    property: /Default/DP-1-2/Position/Y
    type: int
    value: '0'

  - channel: displays
    force_array: 'false'
    property: /Default/DP-1-2/Primary
    type: bool
    value: 'false'

  - channel: displays
    force_array: 'false'
    property: /Default/DP-1-2/Reflection
    type: int
    value: '0'

  - channel: displays
    force_array: 'false'
    property: /Default/DP-1-2/RefreshRate
    type: double
    value: '60.000000'

  - channel: displays
    force_array: 'false'
    property: /Default/DP-1-2/Resolution
    type: string
    value: 1920x1080

  - channel: displays
    force_array: 'false'
    property: /Default/DP-1-2/Rotation
    type: int
    value: '90'

  - channel: displays
    force_array: 'false'
    property: /Default/DP-1-2/Scale/X
    type: double
    value: '1.000000'

  - channel: displays
    force_array: 'false'
    property: /Default/DP-1-2/Scale/Y
    type: double
    value: '1.000000'

  - channel: displays
    force_array: 'false'
    property: /Default/HDMI-1-0
    type: string
    value: LG 32"

  - channel: displays
    force_array: 'false'
    property: /Default/HDMI-1-0/Active
    type: bool
    value: 'true'

  - channel: displays
    force_array: 'false'
    property: /Default/HDMI-1-0/EDID
    type: string
    value: e50b6f8b5c9854ec5f8ed4921b2048f94437167f

  - channel: displays
    force_array: 'false'
    property: /Default/HDMI-1-0/Position/X
    type: int
    value: '1080'

  - channel: displays
    force_array: 'false'
    property: /Default/HDMI-1-0/Position/Y
    type: int
    value: '480'

  - channel: displays
    force_array: 'false'
    property: /Default/HDMI-1-0/Primary
    type: bool
    value: 'true'

  - channel: displays
    force_array: 'false'
    property: /Default/HDMI-1-0/Reflection
    type: int
    value: '0'

  - channel: displays
    force_array: 'false'
    property: /Default/HDMI-1-0/RefreshRate
    type: double
    value: '59.950550'

  - channel: displays
    force_array: 'false'
    property: /Default/HDMI-1-0/Resolution
    type: string
    value: 2560x1440

  - channel: displays
    force_array: 'false'
    property: /Default/HDMI-1-0/Rotation
    type: int
    value: '0'

  - channel: displays
    force_array: 'false'
    property: /Default/HDMI-1-0/Scale/X
    type: double
    value: '1.000000'

  - channel: displays
    force_array: 'false'
    property: /Default/HDMI-1-0/Scale/Y
    type: double
    value: '1.000000'

  - channel: displays
    force_array: 'false'
    property: /Default/eDP-1
    type: string
    value: Laptop

  - channel: displays
    force_array: 'false'
    property: /Default/eDP-1/Active
    type: bool
    value: 'true'

  - channel: displays
    force_array: 'false'
    property: /Default/eDP-1/EDID
    type: string
    value: d8e8c3b3d3bcf218eea802ed9c52bbe3a0086f5a

  - channel: displays
    force_array: 'false'
    property: /Default/eDP-1/Position/X
    type: int
    value: '0'

  - channel: displays
    force_array: 'false'
    property: /Default/eDP-1/Position/Y
    type: int
    value: '0'

  - channel: displays
    force_array: 'false'
    property: /Default/eDP-1/Primary
    type: bool
    value: 'false'

  - channel: displays
    force_array: 'false'
    property: /Default/eDP-1/Reflection
    type: int
    value: '0'

  - channel: displays
    force_array: 'false'
    property: /Default/eDP-1/RefreshRate
    type: double
    value: '60.007752'

  - channel: displays
    force_array: 'false'
    property: /Default/eDP-1/Resolution
    type: string
    value: 1920x1080

  - channel: displays
    force_array: 'false'
    property: /Default/eDP-1/Rotation
    type: int
    value: '0'

  - channel: displays
    force_array: 'false'
    property: /Default/eDP-1/Scale/X
    type: double
    value: '1.000000'

  - channel: displays
    force_array: 'false'
    property: /Default/eDP-1/Scale/Y
    type: double
    value: '1.000000'

  - channel: displays
    force_array: 'false'
    property: /Default/eDP-2
    type: string
    value: Laptop

  - channel: displays
    force_array: 'false'
    property: /Default/eDP-2/Active
    type: bool
    value: 'true'

  - channel: displays
    force_array: 'false'
    property: /Default/eDP-2/EDID
    type: string
    value: d8e8c3b3d3bcf218eea802ed9c52bbe3a0086f5a

  - channel: displays
    force_array: 'false'
    property: /Default/eDP-2/Position/X
    type: int
    value: '0'

  - channel: displays
    force_array: 'false'
    property: /Default/eDP-2/Position/Y
    type: int
    value: '0'

  - channel: displays
    force_array: 'false'
    property: /Default/eDP-2/Primary
    type: bool
    value: 'true'

  - channel: displays
    force_array: 'false'
    property: /Default/eDP-2/Reflection
    type: int
    value: '0'

  - channel: displays
    force_array: 'false'
    property: /Default/eDP-2/RefreshRate
    type: double
    value: '120.015505'

  - channel: displays
    force_array: 'false'
    property: /Default/eDP-2/Resolution
    type: string
    value: 1920x1080

  - channel: displays
    force_array: 'false'
    property: /Default/eDP-2/Rotation
    type: int
    value: '0'

  - channel: displays
    force_array: 'false'
    property: /Default/eDP-2/Scale/X
    type: double
    value: '1.000000'

  - channel: displays
    force_array: 'false'
    property: /Default/eDP-2/Scale/Y
    type: double
    value: '1.000000'

  # display settings, laptop only profile
  - channel: displays
    force_array: 'false'
    property: /ba80724e2db564ce4d9289488bba79e7d492ff19
    type: string
    value: laptop only

  - channel: displays
    force_array: 'false'
    property: /ba80724e2db564ce4d9289488bba79e7d492ff19/eDP-1
    type: string
    value: Laptop

  - channel: displays
    force_array: 'false'
    property: /ba80724e2db564ce4d9289488bba79e7d492ff19/eDP-1/Active
    type: bool
    value: 'true'

  - channel: displays
    force_array: 'false'
    property: /ba80724e2db564ce4d9289488bba79e7d492ff19/eDP-1/EDID
    type: string
    value: d8e8c3b3d3bcf218eea802ed9c52bbe3a0086f5a

  - channel: displays
    force_array: 'false'
    property: /ba80724e2db564ce4d9289488bba79e7d492ff19/eDP-1/Position/X
    type: int
    value: '0'

  - channel: displays
    force_array: 'false'
    property: /ba80724e2db564ce4d9289488bba79e7d492ff19/eDP-1/Position/Y
    type: int
    value: '0'

  - channel: displays
    force_array: 'false'
    property: /ba80724e2db564ce4d9289488bba79e7d492ff19/eDP-1/Primary
    type: bool
    value: 'false'

  - channel: displays
    force_array: 'false'
    property: /ba80724e2db564ce4d9289488bba79e7d492ff19/eDP-1/Reflection
    type: int
    value: '0'

  - channel: displays
    force_array: 'false'
    property: /ba80724e2db564ce4d9289488bba79e7d492ff19/eDP-1/RefreshRate
    type: double
    value: '120.015505'

  - channel: displays
    force_array: 'false'
    property: /ba80724e2db564ce4d9289488bba79e7d492ff19/eDP-1/Resolution
    type: string
    value: 1920x1080

  - channel: displays
    force_array: 'false'
    property: /ba80724e2db564ce4d9289488bba79e7d492ff19/eDP-1/Rotation
    type: int
    value: '0'

  - channel: displays
    force_array: 'false'
    property: /ba80724e2db564ce4d9289488bba79e7d492ff19/eDP-1/Scale/X
    type: double
    value: '1.000000'

  - channel: displays
    force_array: 'false'
    property: /ba80724e2db564ce4d9289488bba79e7d492ff19/eDP-1/Scale/Y
    type: double
    value: '1.000000'

  # display settings, 3 screens profile
  - channel: displays
    force_array: 'false'
    property: /d4df945a4760356ad978ade7ffc60a03c3acbb12
    type: string
    value: 3 screens

  - channel: displays
    force_array: 'false'
    property: /d4df945a4760356ad978ade7ffc60a03c3acbb12/DP-1-2
    type: string
    value: ASUS 27"

  - channel: displays
    force_array: 'false'
    property: /d4df945a4760356ad978ade7ffc60a03c3acbb12/DP-1-2/Active
    type: bool
    value: 'true'

  - channel: displays
    force_array: 'false'
    property: /d4df945a4760356ad978ade7ffc60a03c3acbb12/DP-1-2/EDID
    type: string
    value: 71f8026b5cdd2776c54bd1529eb350fd35526c9e

  - channel: displays
    force_array: 'false'
    property: /d4df945a4760356ad978ade7ffc60a03c3acbb12/DP-1-2/Position/X
    type: int
    value: '0'

  - channel: displays
    force_array: 'false'
    property: /d4df945a4760356ad978ade7ffc60a03c3acbb12/DP-1-2/Position/Y
    type: int
    value: '0'

  - channel: displays
    force_array: 'false'
    property: /d4df945a4760356ad978ade7ffc60a03c3acbb12/DP-1-2/Primary
    type: bool
    value: 'false'

  - channel: displays
    force_array: 'false'
    property: /d4df945a4760356ad978ade7ffc60a03c3acbb12/DP-1-2/Reflection
    type: int
    value: '0'

  - channel: displays
    force_array: 'false'
    property: /d4df945a4760356ad978ade7ffc60a03c3acbb12/DP-1-2/RefreshRate
    type: double
    value: '60.000000'

  - channel: displays
    force_array: 'false'
    property: /d4df945a4760356ad978ade7ffc60a03c3acbb12/DP-1-2/Resolution
    type: string
    value: 1920x1080

  - channel: displays
    force_array: 'false'
    property: /d4df945a4760356ad978ade7ffc60a03c3acbb12/DP-1-2/Rotation
    type: int
    value: '90'

  - channel: displays
    force_array: 'false'
    property: /d4df945a4760356ad978ade7ffc60a03c3acbb12/DP-1-2/Scale/X
    type: double
    value: '1.000000'

  - channel: displays
    force_array: 'false'
    property: /d4df945a4760356ad978ade7ffc60a03c3acbb12/DP-1-2/Scale/Y
    type: double
    value: '1.000000'

  - channel: displays
    force_array: 'false'
    property: /d4df945a4760356ad978ade7ffc60a03c3acbb12/HDMI-1-0
    type: string
    value: LG 32"

  - channel: displays
    force_array: 'false'
    property: /d4df945a4760356ad978ade7ffc60a03c3acbb12/HDMI-1-0/Active
    type: bool
    value: 'true'

  - channel: displays
    force_array: 'false'
    property: /d4df945a4760356ad978ade7ffc60a03c3acbb12/HDMI-1-0/EDID
    type: string
    value: e50b6f8b5c9854ec5f8ed4921b2048f94437167f

  - channel: displays
    force_array: 'false'
    property: /d4df945a4760356ad978ade7ffc60a03c3acbb12/HDMI-1-0/Position/X
    type: int
    value: '1080'

  - channel: displays
    force_array: 'false'
    property: /d4df945a4760356ad978ade7ffc60a03c3acbb12/HDMI-1-0/Position/Y
    type: int
    value: '480'

  - channel: displays
    force_array: 'false'
    property: /d4df945a4760356ad978ade7ffc60a03c3acbb12/HDMI-1-0/Primary
    type: bool
    value: 'true'

  - channel: displays
    force_array: 'false'
    property: /d4df945a4760356ad978ade7ffc60a03c3acbb12/HDMI-1-0/Reflection
    type: int
    value: '0'

  - channel: displays
    force_array: 'false'
    property: /d4df945a4760356ad978ade7ffc60a03c3acbb12/HDMI-1-0/RefreshRate
    type: double
    value: '59.950550'

  - channel: displays
    force_array: 'false'
    property: /d4df945a4760356ad978ade7ffc60a03c3acbb12/HDMI-1-0/Resolution
    type: string
    value: 2560x1440

  - channel: displays
    force_array: 'false'
    property: /d4df945a4760356ad978ade7ffc60a03c3acbb12/HDMI-1-0/Rotation
    type: int
    value: '0'

  - channel: displays
    force_array: 'false'
    property: /d4df945a4760356ad978ade7ffc60a03c3acbb12/HDMI-1-0/Scale/X
    type: double
    value: '1.000000'

  - channel: displays
    force_array: 'false'
    property: /d4df945a4760356ad978ade7ffc60a03c3acbb12/HDMI-1-0/Scale/Y
    type: double
    value: '1.000000'

  - channel: displays
    force_array: 'false'
    property: /d4df945a4760356ad978ade7ffc60a03c3acbb12/eDP-1
    type: string
    value: Laptop

  - channel: displays
    force_array: 'false'
    property: /d4df945a4760356ad978ade7ffc60a03c3acbb12/eDP-1/Active
    type: bool
    value: 'true'

  - channel: displays
    force_array: 'false'
    property: /d4df945a4760356ad978ade7ffc60a03c3acbb12/eDP-1/EDID
    type: string
    value: d8e8c3b3d3bcf218eea802ed9c52bbe3a0086f5a

  - channel: displays
    force_array: 'false'
    property: /d4df945a4760356ad978ade7ffc60a03c3acbb12/eDP-1/Position/X
    type: int
    value: '3640'

  - channel: displays
    force_array: 'false'
    property: /d4df945a4760356ad978ade7ffc60a03c3acbb12/eDP-1/Position/Y
    type: int
    value: '1200'

  - channel: displays
    force_array: 'false'
    property: /d4df945a4760356ad978ade7ffc60a03c3acbb12/eDP-1/Primary
    type: bool
    value: 'false'

  - channel: displays
    force_array: 'false'
    property: /d4df945a4760356ad978ade7ffc60a03c3acbb12/eDP-1/Reflection
    type: int
    value: '0'

  - channel: displays
    force_array: 'false'
    property: /d4df945a4760356ad978ade7ffc60a03c3acbb12/eDP-1/RefreshRate
    type: double
    value: '120.001629'

  - channel: displays
    force_array: 'false'
    property: /d4df945a4760356ad978ade7ffc60a03c3acbb12/eDP-1/Resolution
    type: string
    value: 1280x720

  - channel: displays
    force_array: 'false'
    property: /d4df945a4760356ad978ade7ffc60a03c3acbb12/eDP-1/Rotation
    type: int
    value: '0'

  - channel: displays
    force_array: 'false'
    property: /d4df945a4760356ad978ade7ffc60a03c3acbb12/eDP-1/Scale/X
    type: double
    value: '1.000000'

  - channel: displays
    force_array: 'false'
    property: /d4df945a4760356ad978ade7ffc60a03c3acbb12/eDP-1/Scale/Y
    type: double
    value: '1.000000'
