---
- name: Include spryker VPN tasks
  ansible.builtin.include_tasks: vpn.yaml

- name: Include spryker git tasks
  ansible.builtin.include_tasks: git.yaml

- name: Include spryker terraform tasks
  ansible.builtin.include_tasks: terraform.yaml

- name: Install some required deb packages
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - python3-hvac
      - awscli

- name: Include spryker sre-bot-devel tasks
  ansible.builtin.include_tasks: sre-bot-devel.yaml
