---
- name: Include spryker VPN tasks
  ansible.builtin.include_tasks: vpn.yaml

- name: Include spryker git tasks
  ansible.builtin.include_tasks: git.yaml

- name: Include spryker terraform tasks
  ansible.builtin.include_tasks: terraform.yaml
