---
# from https://developer.hashicorp.com/terraform/downloads
- name: Install terraform
  ansible.builtin.include_tasks: "{{ role_path }}/../common/tasks/apt-install-from-repository.yml"
  vars:
    conf:
      shortname: terraform
      repo_spec: https://apt.releases.hashicorp.com bookworm main
      key_url: https://apt.releases.hashicorp.com/gpg
      packages:
        - terraform

# from https://terragrunt.gruntwork.io/docs/getting-started/install/
# and https://github.com/gruntwork-io/terragrunt/releases
- name: Install terragrunt original
  ansible.builtin.include_tasks: "{{ role_path }}/../common/tasks/binary-install-from-url.yaml"
  vars:
    binary:
      name: terragrunt
      version: "v0.52.5"
      version_command: "terragrunt_orig --version"
      path: /usr/local/bin/terragrunt_orig
      url: https://github.com/gruntwork-io/terragrunt/releases/download/v0.52.5/terragrunt_linux_amd64
      checksum: sha256:c22755640122bddf78d3c7311e0e1d66fcdab8a7c1d1e876e3fca60edb5f1a21
      unpack: false

- name: Install terragrunt safety wrapper
  become: true
  ansible.builtin.copy:
    src: terragrunt
    dest: /usr/local/bin/terragrunt
    mode: "0755"

# from https://github.com/terraform-docs/terraform-docs/
- name: Install terraform-docs
  ansible.builtin.include_tasks: "{{ role_path }}/../common/tasks/binary-install-from-url.yaml"
  vars:
    binary:
      name: terraform-docs
      version: "v0.16.0"
      version_command: "terraform-docs --version"
      path: /usr/local/bin/terraform-docs
      url: https://github.com/terraform-docs/terraform-docs/releases/download/v0.16.0/terraform-docs-v0.16.0-linux-amd64.tar.gz
      checksum: sha256:328c16cd6552b3b5c4686b8d945a2e2e18d2b8145b6b66129cd5491840010182
      unpack: yes

# from https://github.com/terraform-linters/tflint
- name: Install tflint
  ansible.builtin.include_tasks: "{{ role_path }}/../common/tasks/binary-install-from-url.yaml"
  vars:
    binary:
      name: tflint
      version: "0.49.0"
      version_command: "tflint --version"
      path: /usr/local/bin/tflint
      url: https://github.com/terraform-linters/tflint/releases/download/v0.49.0/tflint_linux_amd64.zip
      checksum: sha256:56d862054e8f71e3ba392c6617fca2d730b5ecdf8a4a0768ba6087406dcc7d63
      unpack: yes
