---
# see also: https://spryker.atlassian.net/wiki/spaces/DIO/pages/807469142/Spryker+OpenVPN+configuration

- name: Install network-manager-openvpn package
  become: true
  ansible.builtin.apt:
    name: network-manager-openvpn
    state: latest

- name: Create secrets directory
  ansible.builtin.file:
    dest: /home/{{ user }}/.cert/nm-openvpn/
    state: directory
    mode: "0755"

- name: Ensure secrets exists
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /home/{{ user }}/.cert/nm-openvpn/
    mode: "0600"
  loop:
    - "{{ role_path }}/secrets/spryker-vpn-ca.pem"
    - "{{ role_path }}/secrets/spryker-vpn-cert.pem"
    - "{{ role_path }}/secrets/spryker-vpn-key.pem"
    - "{{ role_path }}/secrets/spryker-vpn-tls-auth.pem"
  register: nm_secrets

- name: Install network manager config file
  become: true
  ansible.builtin.copy:
    src: spryker-vpn.nmconnection
    dest: /etc/NetworkManager/system-connections/
    mode: "0600"
  register: nm_config_file

- name: See if network manager knows about the VPN
  ansible.builtin.command:
    cmd: nmcli connection show spryker-vpn
  register: nmcli_connection_show
  # 0 == ok, 10 == not found
  failed_when: nmcli_connection_show.rc not in [0, 10]
  # never changed otherwise is always changed
  changed_when: false

- name: Reload network manager connection
  become: true
  ansible.builtin.command:
    cmd: nmcli connection reload
  when: >
    nmcli_connection_show.rc == 10 or
    nm_secrets.changed or
    nm_config_file.changed
  register: nmcli_connection_reload
  # always changed if run
  changed_when: true

- name: Check if the VPN is active
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      set -o pipefail
      nmcli connection show --active | grep -q spryker-vpn
  register: nmcli_connection_show
  # 0 == ok, 1 == not found
  failed_when: nmcli_connection_show.rc not in [0 , 1]
  # never changed otherwise is always changed
  changed_when: false

- name: Start VPN
  become: true
  ansible.builtin.command:
    cmd: nmcli connection up spryker-vpn
  when: nmcli_connection_reload.changed or nmcli_connection_show.rc == 1
  # always changed if run
  changed_when: true
