#!/bin/bash

system_terragrunt="/usr/local/bin/terragrunt_orig"
root="tfcloud"
this="$(pwd)"

warning() {
    echo "WARNING: maybe wrong environment directory? Confirm (y/N)"
    read -r confirm
    if [ "${confirm}" != "y" ] ; then
        echo "... glad I asked ..."
        exit 1
    fi
}

get_ppid() {
    local pid=${1:?"Missing input pid"}
    ps -o ppid= "${pid}" | tr -d ' '
}

get_pid_name() {
    local pid=${1:?"Missing input pid"}
    ps -o comm= "${pid}"
}

check_ppid_tree_names() {
    local contains=${1:?"Missing input strings"}
    local ppid

    ppid=$(get_ppid $$)
    while [ "$ppid" != "0" ] ; do
        pid_name=$(get_pid_name "${ppid}")
        for contain in ${contains} ; do
            if grep -q "${contain}" <<< "${pid_name}" ; then
                return 0
            fi
        done
        ppid=$(get_ppid "${ppid}")
    done

    return 1
}

if ! check_ppid_tree_names "git pre-commit" ; then
    dirname=$(awk -F'/' '{print $NF}' <<< "${this}")
    if [ "${dirname}" == "${root}" ] ; then
        warning
    fi

    dirname=$(awk -F'/' '{print $(NF-2)"/"$(NF-1)"/"$(NF)}' <<< "${this}")
    if ! grep -q "${root}/.*/.*" <<< "${dirname}" ; then
        warning
    fi
fi

${system_terragrunt} "$@"
