#!/bin/bash

system_terragrunt="/usr/local/bin/terragrunt_orig"
root="tfcloud"
this="$(pwd)"

warning() {
    echo "WARNING: maybe wrong environment directory? Confirm (y/N)"
    read -r confirm
    if [ "${confirm}" != "y" ] ; then
        echo "... glad I asked ..."
        exit 1
    fi
}

get_ppid() {
    local pid=${1:?"Missing input pid"}
    ps -o ppid= "${pid}" | tr -d ' '
}

get_pid_name() {
    local pid=${1:?"Missing input pid"}
    ps -o comm= "${pid}"
}

get_ppid_tree_names() {
    local ppid

    ppid=$(get_ppid $$)
    while [ "$ppid" != "0" ] ; do
        name=$(get_pid_name "${ppid}")
        echo "${name}"
        ppid=$(get_ppid "${ppid}")
    done
}

check_ppid_tree_contains() {
    local contains=${1:?"Missing input argument"}
    if grep -q "${contains}" <<< "$(get_ppid_tree_names)" ; then
        return 0
    fi
    return 1
}

if ! check_ppid_tree_contains "pre-commit" ; then
    dirname=$(awk -F'/' '{print $NF}' <<< "${this}")
    if [ "${dirname}" == "${root}" ] ; then
        warning
    fi

    dirname=$(awk -F'/' '{print $(NF-2)"/"$(NF-1)"/"$(NF)}' <<< "${this}")
    if ! grep -q "${root}/.*/.*" <<< "${dirname}" ; then
        warning
    fi
fi

${system_terragrunt} "$@"
