#!/bin/bash

system_terragrunt="/usr/local/bin/terragrunt_orig"
root="tfcloud"
this="$(pwd)"

warning() {
    echo "WARNING: maybe wrong environment directory? Confirm (y/N)"
    read -r confirm
    if [ "${confirm}" != "y" ] ; then
        echo "... glad I asked ..."
        exit 1
    fi
}

dirname=$(awk -F'/' '{print $NF}' <<< "${this}")
if [ "${dirname}" == "${root}" ] ; then
    warning
fi

dirname=$(awk -F'/' '{print $(NF-2)"/"$(NF-1)"/"$(NF)}' <<< "${this}")
if ! grep -q "${root}/.*/.*" <<< "${dirname}" ; then
    warning
fi

${system_terragrunt} "$@"
