---
- name: ensure destination dirs exist
  tags: git
  become: true
  become_user: "{{user}}"
  ansible.builtin.file:
    dest: "/home/{{user}}/git/{{item.dir}}"
    state: directory
  loop: "{{git_repos}}"

- name: ensure local clone exists
  tags: git
  become: true
  become_user: "{{user}}"
  ansible.builtin.command:
    cmd: "git clone --quiet {{item.url}} /home/{{user}}/git/{{item.dir}}"
    creates: "/home/{{user}}/git/{{item.dir}}/.git"
  loop: "{{git_repos}}"

- name: configure email
  tags: git
  become: true
  become_user: "{{user}}"
  ansible.builtin.command: "git -C /home/{{user}}/git/{{item.dir}}/ config user.email {{email}}"
  when: email is defined
  changed_when: false
  loop: "{{git_repos}}"

- name: pull and fast-forward
  tags: git
  become: true
  become_user: "{{user}}"
  ansible.builtin.command: "git -C /home/{{user}}/git/{{item.dir}}/ pull --rebase --ff-only --all --no-autostash --quiet"
  ignore_errors: true
  changed_when: false
  failed_when: false
  async: 45
  poll: 0
  loop: "{{git_repos}}"
