---
- name: Install git-related software
  become: true
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - git
      - stgit

- name: install git configuration dotfiles
  include_tasks: "{{ role_path }}/../dotfiles/tasks/link_dotfiles.yml"
  vars:
    dotfiles:
      - gitconfig
