---
- name: Install git-related software
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - git
      - gh
      - git-lfs
      - pre-commit
      - git-crypt
      - git-delta
      - gitsign

- name: Ensure secrets are decrypted
  ansible.builtin.command:
    cmd: git crypt unlock
    chdir: "{{ role_path }}/../.."
  register: git_crypt_unlock
  # always changed
  changed_when: true
  # allow me to work on the repo and run the playbook without this failing
  failed_when: >
    git_crypt_unlock.rc != 0 and
    "Please commit your changes or 'git stash' them before running 'git-crypt unlock'." not in git_crypt_unlock.stderr

# see https://github.com/getsops/sops
# releases from https://github.com/getsops/sops/releases
- name: Install SOPS
  become: true
  ansible.builtin.apt:
    deb: https://github.com/getsops/sops/releases/download/v3.8.1/sops_3.8.1_amd64.deb

- name: Install git configuration dotfiles
  include_tasks: "{{ role_path }}/../dotfiles/tasks/link_dotfiles.yml"
  vars:
    dotfiles:
      - gitconfig
      - gitignore

- name: Install github CLI config dotfiles
  ansible.builtin.include_tasks: "{{ role_path }}/../dotfiles/tasks/link_dotfiles.yml"
  vars:
    dotfiles:
      - config/gh/config.yml
      - config/gh/hosts.yml

- name: Fetch git lfs files
  ansible.builtin.command:
    cmd: git lfs fetch
    chdir: "{{ role_path }}/../../"

- name: Checkout git lfs files
  ansible.builtin.command:
    cmd: git lfs checkout
    chdir: "{{ role_path }}/../../"

- name: Install custom git library
  become: true
  ansible.builtin.copy:
    src: "arturo-git-lib.sh"
    dest: /usr/local/share/arturo-git-lib.sh
    owner: root
    group: root
    mode: "0755"

- name: Install custom git scripts
  become: true
  ansible.builtin.copy:
    src: "{{ item }}.sh"
    dest: /usr/local/bin/{{ item }}
    owner: root
    group: root
    mode: "0755"
  loop:
    - gr
    - grf
    - ge
    - gpr
    - ghr
    - ghm
    - grm
    - glm
    - gwo
    - gscc

- name: Clone some github repos
  include_tasks: "{{ role_path }}/../git/tasks/clone.yml"
  vars:
    email: arturo.bg@arturo.bg
    git_repos:
      - url: git@github.com:aborrero/ansible-setup.git
        dir: github/ansible-setup
      - url: git@github.com:aborrero/alfabravo.org.git
        dir: github/alfabravo.org
      - url: git@github.com:aborrero/ral-arturo.org.git
        dir: github/ral-arturo.org
      - url: git@github.com:aborrero/sys-avenger.git
        dir: github/sys-avenger
      - url: git@github.com:aborrero/arturo.bg.git
        dir: github/arturo.bg
      - url: git@github.com:aborrero/nftables-tracer.git
        dir: github/nftables-tracer

# from https://github.com/stacked-git/stgit/releases
- name: Install stgit
  become: true
  ansible.builtin.apt:
    deb: https://github.com/stacked-git/stgit/releases/download/v2.4.5/stgit_2.4.5-1_amd64.deb

# see https://book.git-ps.sh/
- name: Install git patch stack cargo package
  community.general.cargo:
    name: "gps"
    state: "latest"

# see https://github.com/sigstore/gitsign/tree/main/cmd/gitsign-credential-cache
- name: Create systemd files for gitsign-credential-cache
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/systemd/user/{{ item }}
    owner: root
    group: root
    mode: "0644"
  loop:
    - gitsign-credential-cache.service
    - gitsign-credential-cache.socket

- name: Enable systemd service for gitsign-credential-cache
  become: true
  become_user: "{{ user }}"
  ansible.builtin.systemd:
    name: gitsign-credential-cache.service
    enabled: true
    state: started
    scope: user
    daemon_reload: true
  # affected by https://github.com/ansible/ansible/issues/75542 or similar
  changed_when: false
