---
- name: install git-related software
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - git
      - stgit
      - gh

- name: Install git configuration dotfiles
  include_tasks: "{{ role_path }}/../dotfiles/tasks/link_dotfiles.yml"
  vars:
    dotfiles:
      - gitconfig
      - gitignore

- name: Install github CLI config dotfiles
  ansible.builtin.include_tasks: "{{ role_path }}/../dotfiles/tasks/link_dotfiles.yml"
  vars:
    dotfiles:
      - config/gh/config.yml
      - config/gh/hosts.yml


- name: Install custom git scripts
  become: true
  ansible.builtin.copy:
    src: "{{ item }}.sh"
    dest: /usr/local/bin/{{ item }}
    owner: root
    group: root
    mode: "0755"
  loop:
    - gr
    - grf
    - ge
    - gpr

- name: clone some github repos
  include_tasks: "{{ role_path }}/../git/tasks/clone.yml"
  vars:
    email: arturo.bg@arturo.bg
    git_repos:
      - url: git@github.com:aborrero/ansible-setup.git
        dir: github/ansible-setup
      - url: git@github.com:aborrero/alfabravo.org.git
        dir: github/alfabravo.org
      - url: git@github.com:aborrero/ral-arturo.org.git
        dir: github/ral-arturo.org
      - url: git@github.com:aborrero/sys-avenger.git
        dir: github/sys-avenger
      - url: git@github.com:aborrero/arturo.bg.git
        dir: github/arturo.bg
