# hit <tab> to edit before enter
# TODO: buggy on bash, see https://github.com/atuinsh/atuin/pull/1342
#enter_accept = true

## enable or disable automatic sync
auto_sync = true

## enable or disable automatic update checks
update_check = true

## how often to sync history. note that this is only triggered when a command
## is ran, so sync intervals may well be longer
## set it to 0 to sync after every command
sync_frequency = 0

style = "full"

[sync]
records = true
