---
- name: ensure config directories exists
  become: true
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
  loop:
    - /etc/nftables.d/
    - /etc/systemd/system/nftables.service.d/

- name: install config file
  become: true
  ansible.builtin.copy:
    src: ruleset.nft
    dest: /etc/nftables.d/ruleset.nft
  register: config

- name: install service file
  become: true
  ansible.builtin.copy:
    dest: /etc/systemd/system/nftables.service.d/ansible-setup-override.conf
    content: |
      [Service]
      ExecStart=
      ExecStart=/usr/sbin/nft -f /etc/nftables.d/ruleset.nft
      ExecReload=
      ExecReload=/usr/sbin/nft -f /etc/nftables.d/ruleset.nft
  register: service

- name: enable nftables systemd service
  become: true
  ansible.builtin.systemd:
    name: nftables.service
    enabled: true

- name: reload systemd on service changes
  become: true
  ansible.builtin.shell: systemctl daemon-reload
  when: service.changed

- name: restart nftables service
  become: true
  ansible.builtin.systemd:
    name: nftables.service
    state: restarted
  when: config.changed or service.changed

# this is shipped by the debian package, but we don't use it
- name: Remove unused file /etc/nftables.conf
  become: true
  ansible.builtin.file:
    path: /etc/nftables.conf
    state: absent
