---
- name: make sure user ansible-setup exists
  become: true
  ansible.builtin.user:
    name: ansible-setup
    create_home: true
    home: /var/local/ansible-setup
    system: true
    shell: /usr/sbin/nologin

- name: enable passwordless sudo for the ansible-setup user
  become: true
  ansible.builtin.lineinfile:
    create: true
    dest: /etc/sudoers.d/ansible-setup
    state: present
    line: "%ansible-setup ALL = (ALL) NOPASSWD: ALL"

- name: make sure ~/.ansible-setup/ exists
  become: true
  become_user: "{{user}}"
  ansible.builtin.file:
    dest: /home/{{user}}/.ansible-setup/
    state: directory

- name: write hash of the repo to a ~/.ansible-setup/last_run_hash
  become: true
  become_user: "{{user}}"
  ansible.builtin.shell: git --git-dir=/home/{{user}}/git/github/ansible-setup/.git rev-parse HEAD > /home/{{user}}/.ansible-setup/last_run_hash

