---
- name: update single repository defined in {{file}}
  tags: apt
  become: true
  ansible.builtin.shell: apt-get update -o Dir::Etc::sourcelist="{{file}}" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
  # never mark this task as changed (otherwise is always changed)
  changed_when: False
