---
- name: Include email tasks
  ansible.builtin.include_tasks: email.yaml

- name: Include rclone tasks
  ansible.builtin.include_tasks: rclone.yml

- name: Include atuin tasks
  ansible.builtin.include_tasks: atuin.yaml

- name: Add user to sudo Unix group
  become: true
  ansible.builtin.user:
    name: "{{ user }}"
    groups: sudo
    append: true

- name: Install custom sources.list
  tags: apt
  become: true
  ansible.builtin.copy:
    src: sources.list
    dest: /etc/apt/sources.list
    mode: "0644"

- name: Install a list of packages to their latest version
  tags: apt
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - wget
      - curl
      - htop
      - liquidprompt
      - aptitude
      - cmatrix
      - ansible-lint
      - firmware-iwlwifi
      - firmware-misc-nonfree
      - firmware-linux-free
      - firmware-nvidia-gsp
      - xserver-xorg-video-nvidia
      - console-setup
      - xfonts-terminus
      - tcpdump
      - shellcheck
      - ethtool
      - tree
      - fzf
      - python3-pygments
      - bat
      - npm
      - jq
      - cargo

- name: Install nostromo-specific packages
  tags:
    - apt
    - nostromo
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - firmware-sof-signed
  when: ansible_facts['nodename'] == 'nostromo'

- name: Upgrade installed packages
  tags: apt
  become: true
  ansible.builtin.apt:
    upgrade: true

- name: Remove useless packages from the cache
  tags: apt
  become: true
  ansible.builtin.apt:
    autoclean: true

- name: Remove dependencies that are no longer required
  tags: apt
  become: true
  ansible.builtin.apt:
    autoremove: true

- name: Maintain /etc/default/grub file
  become: true
  ansible.builtin.copy:
    src: grub
    dest: /etc/default/grub
    mode: "0644"
  register: grub

- name: Run update-grub
  # I'm lazy:
  # noqa: no-handler
  become: true
  ansible.builtin.command: update-grub
  when: grub.changed
  register: update_grub
  changed_when: update_grub.changed

- name: Install modprobe config file
  become: true
  ansible.builtin.copy:
    src: modprobe_pcspkr.conf
    dest: /etc/modprobe.d/modpprobe_pcspkr.conf
    mode: "0644"

- name: Install /etc/default/console-setup file
  become: true
  ansible.builtin.copy:
    src: console-setup
    dest: /etc/default/console-setup
    mode: "0644"

# NOTE: nix disabled for now, it eats the space on /nix which is usually the root partition
# changing it is not simple with the debian installation method
#- name: Include nix tasks
#  ansible.builtin.include_tasks: nix.yaml

# log viewer, see https://github.com/tstack/lnav
- name: Install lnav
  ansible.builtin.include_tasks: "{{ role_path }}/../common/tasks/binary-install-from-url.yaml"
  vars:
    binary:
      name: "lnav"
      version: "0.11.2"
      version_command: "lnav -V"
      path: "/usr/local/bin/lnav"
      url: "https://github.com/tstack/lnav/releases/download/v0.11.2/lnav-0.11.2-x86_64-linux-musl.zip"
      # note: calculated by hand, they don't provide this
      checksum: "sha256:6515598ca4985ec42daeafbae7eb5c7c6d7e94a11f88666d157b3d363aa391ff"
      unpack: true

# zellij, https://zellij.dev/ from https://github.com/zellij-org/zellij/releases
- name: Install zellij
  ansible.builtin.include_tasks: "{{ role_path }}/../common/tasks/binary-install-from-url.yaml"
  vars:
    binary:
      name: "zellij"
      version: "0.39.2"
      version_command: "zellij --version"
      path: "/usr/local/bin/zellij"
      url: "https://github.com/zellij-org/zellij/releases/download/v0.39.2/zellij-x86_64-unknown-linux-musl.tar.gz"
      # NOTE: wrong sha256 published, see https://github.com/zellij-org/zellij/issues/3149
      checksum: "sha256:9203da2887042b4d8a3b2753e475f812fa60aff6955ffbf0632c0fbfcfaa4a81"
      unpack: true

# see https://github.com/mikefarah/yq/releases
- name: Install yq
  ansible.builtin.include_tasks: "{{ role_path }}/../common/tasks/binary-install-from-url.yaml"
  vars:
    binary:
      name: "yq"
      version: "4.44.1"
      version_command: "yq --version"
      path: "/usr/local/bin/yq"
      url: "https://github.com/mikefarah/yq/releases/download/v4.44.1/yq_linux_amd64"
      # NOTE: weird script is required to get this script
      checksum: "sha256:6dc2d0cd4e0caca5aeffd0d784a48263591080e4a0895abe69f3a76eb50d1ba3"
      unpack: false

- name: Install initramfs-tools config file
  become: true
  ansible.builtin.copy:
    src: initramfs-tools/conf.d/modules
    dest: /etc/initramfs-tools/conf.d/modules
    mode: "0644"
