---
- name: Include email tasks
  ansible.builtin.include_tasks: email.yaml

- name: Include rclone tasks
  ansible.builtin.include_tasks: rclone.yml

- name: Include atuin tasks
  ansible.builtin.include_tasks: atuin.yaml

- name: Add user to sudo Unix group
  become: true
  ansible.builtin.user:
    name: "{{ user }}"
    groups: sudo
    append: true

- name: Install apt configuration
  become: true
  ansible.builtin.copy:
    src: apt/
    dest: /etc/apt/
    mode: "0644"

- name: Install apt configuration for nostromo
  become: true
  ansible.builtin.copy:
    src: apt_nostromo/
    dest: /etc/apt/
    mode: "0644"
  # the nostromo laptop doesn't work well with newer kernel, install apt pin
  when: ansible_facts['nodename'] == 'nostromo'


- name: Install a list of packages to their latest version
  tags: apt
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - wget
      - curl
      - htop
      - liquidprompt
      - aptitude
      - cmatrix
      - ansible-lint
      - firmware-iwlwifi
      - firmware-misc-nonfree
      - firmware-linux-free
      - console-setup
      - xfonts-terminus
      - tcpdump
      - shellcheck
      - ethtool
      - tree
      - fzf
      - python3-pygments
      - bat
      - npm
      - jq
      - cargo

- name: Install nvidia-related packages
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - firmware-nvidia-gsp
      - xserver-xorg-video-nvidia
  when: ansible_facts['nodename'] == 'nostromo' or ansible_facts['nodename'] == 'endurance'

- name: Install nostromo-specific packages
  tags:
    - apt
    - nostromo
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - firmware-sof-signed
  when: ansible_facts['nodename'] == 'nostromo'

- name: Upgrade installed packages
  tags: apt
  become: true
  ansible.builtin.apt:
    upgrade: true

- name: Remove useless packages from the cache
  tags: apt
  become: true
  ansible.builtin.apt:
    autoclean: true

- name: Remove dependencies that are no longer required
  tags: apt
  become: true
  ansible.builtin.apt:
    autoremove: true

- name: Maintain /etc/default/grub file
  become: true
  ansible.builtin.copy:
    src: grub
    dest: /etc/default/grub
    mode: "0644"
  register: grub

- name: Run update-grub
  # I'm lazy:
  # noqa: no-handler
  become: true
  ansible.builtin.command: update-grub
  when: grub.changed
  register: update_grub
  changed_when: update_grub.changed

- name: Install modprobe config file
  become: true
  ansible.builtin.copy:
    src: modprobe_pcspkr.conf
    dest: /etc/modprobe.d/modpprobe_pcspkr.conf
    mode: "0644"

- name: Install /etc/default/console-setup file
  become: true
  ansible.builtin.copy:
    src: console-setup
    dest: /etc/default/console-setup
    mode: "0644"

# see https://github.com/mikefarah/yq/releases
- name: Install yq
  ansible.builtin.include_tasks: "{{ role_path }}/../common/tasks/binary-install-from-url.yaml"
  vars:
    binary:
      name: "yq"
      version: "4.44.1"
      version_command: "yq --version"
      path: "/usr/local/bin/yq"
      url: "https://github.com/mikefarah/yq/releases/download/v4.44.1/yq_linux_amd64"
      # NOTE: weird script is required to get this script
      checksum: "sha256:6dc2d0cd4e0caca5aeffd0d784a48263591080e4a0895abe69f3a76eb50d1ba3"
      unpack: false

- name: Install initramfs-tools config file
  become: true
  ansible.builtin.copy:
    src: initramfs-tools/conf.d/modules
    dest: /etc/initramfs-tools/conf.d/modules
    mode: "0644"
