---
- include_tasks: ansible-setup.yml
- include_tasks: rclone.yml

- name: Add user to sudo Unix group
  become: true
  ansible.builtin.user:
    name: '{{ user }}'
    groups: sudo
    append: yes

- name: Install custom sources.list
  tags: apt
  become: true
  ansible.builtin.copy:
    src: sources.list
    dest: /etc/apt/sources.list

- name: install a list of packages to their latest version
  tags: cli
  become: true
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - wget
      - curl
      - htop
      - liquidprompt
      - aptitude
      - cmatrix
      - ansible-lint
      - firmware-iwlwifi
      - firmware-misc-nonfree
      - firmware-linux-free
      - firmware-nvidia-gsp
      - xserver-xorg-video-nvidia
      - console-setup
      - xfonts-terminus
      - tcpdump
      - shellcheck

- name: install nostromo-specific packages
  tags: apt nostromo
  become: true
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - firmware-sof-signed
  when: ansible_facts['nodename'] == 'nostromo'

- name: upgrade installed packages
  tags: package-manager
  become: true
  apt:
    upgrade: true

- name: remove useless packages from the cache
  tags: package-manager
  become: true
  apt:
    autoclean: true

- name: remove dependencies that are no longer required
  tags: package-manager
  become: true
  apt:
    autoremove: true

- name: maintain /etc/default/grub file
  become: true
  ansible.builtin.copy:
    src: grub
    dest: /etc/default/grub
  register: grub

- name: update-grub
  become: true
  ansible.builtin.command: update-grub
  when: grub.changed

- name: Install modprobe config file
  become: true
  ansible.builtin.copy:
    src: modprobe_pcspkr.conf
    dest: /etc/modprobe.d/modpprobe_pcspkr.conf

- name: Install /etc/default/console-setup file
  become: true
  ansible.builtin.copy:
    src: console-setup
    dest: /etc/default/console-setup
