---
- name: Include rclone tasks
  ansible.builtin.include_tasks: rclone.yml

- name: Add user to sudo Unix group
  become: true
  ansible.builtin.user:
    name: "{{ user }}"
    groups: sudo
    append: true

- name: Install custom sources.list
  tags: apt
  become: true
  ansible.builtin.copy:
    src: sources.list
    dest: /etc/apt/sources.list
    mode: "0644"

- name: Install a list of packages to their latest version
  tags: apt
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - wget
      - curl
      - htop
      - liquidprompt
      - aptitude
      - cmatrix
      - ansible-lint
      - firmware-iwlwifi
      - firmware-misc-nonfree
      - firmware-linux-free
      - firmware-nvidia-gsp
      - xserver-xorg-video-nvidia
      - console-setup
      - xfonts-terminus
      - tcpdump
      - shellcheck
      - ethtool
      - tree
      - fzf
      - python3-pygments
      - bat
      - npm

- name: Install nostromo-specific packages
  tags:
    - apt
    - nostromo
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - firmware-sof-signed
  when: ansible_facts['nodename'] == 'nostromo'

- name: Upgrade installed packages
  tags: apt
  become: true
  ansible.builtin.apt:
    upgrade: true

- name: Remove useless packages from the cache
  tags: apt
  become: true
  ansible.builtin.apt:
    autoclean: true

- name: Remove dependencies that are no longer required
  tags: apt
  become: true
  ansible.builtin.apt:
    autoremove: true

- name: Maintain /etc/default/grub file
  become: true
  ansible.builtin.copy:
    src: grub
    dest: /etc/default/grub
    mode: "0644"
  register: grub

- name: Run update-grub
  # I'm lazy:
  # noqa: no-handler
  become: true
  ansible.builtin.command: update-grub
  when: grub.changed
  register: update_grub
  changed_when: update_grub.changed

- name: Install modprobe config file
  become: true
  ansible.builtin.copy:
    src: modprobe_pcspkr.conf
    dest: /etc/modprobe.d/modpprobe_pcspkr.conf
    mode: "0644"

- name: Install /etc/default/console-setup file
  become: true
  ansible.builtin.copy:
    src: console-setup
    dest: /etc/default/console-setup
    mode: "0644"

# see https://atuin.sh/
# releases from https://github.com/atuinsh/atuin/releases
- name: Install atuin
  become: true
  ansible.builtin.apt:
    deb: https://github.com/atuinsh/atuin/releases/download/v18.0.1/atuin_18.0.1_amd64.deb

- name: Include nix tasks
  ansible.builtin.include_tasks: nix.yaml

# log viewer, see https://github.com/tstack/lnav
- name: Install lnav
  ansible.builtin.include_tasks: "{{ role_path }}/../common/tasks/binary-install-from-url.yaml"
  vars:
    binary:
      name: "lnav"
      version: "0.11.2"
      version_command: "lnav -V"
      path: "/usr/local/bin/lnav"
      url: "https://github.com/tstack/lnav/releases/download/v0.11.2/lnav-0.11.2-x86_64-linux-musl.zip"
      # note: calculated by hand, they don't provide this
      checksum: "sha256:6515598ca4985ec42daeafbae7eb5c7c6d7e94a11f88666d157b3d363aa391ff"
      unpack: true
