---
# see also /usr/share/doc/nix-bin/README.Debian

- name: Install nix
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - nix

- name: Add user to nix-users Unix group
  become: true
  ansible.builtin.user:
    name: "{{ user }}"
    groups: "nix-users"
    append: true

- name: Configure nix channel
  ansible.builtin.command:
    cmd: "nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs"
  # mark as never changed, otherwise is always changed
  changed_when: false

- name: Update nix channels
  ansible.builtin.command:
    cmd: "nix-channel --update"
  # mark as never changed, otherwise is always changed
  changed_when: false
