---
- name: Install rclone
  tags: rclone
  become: true
  ansible.builtin.apt:
    name: rclone
    state: present

- name: Install rclone config file
  tags: rclone
  ansible.builtin.include_tasks: "{{ role_path }}/../dotfiles/tasks/link_dotfiles.yml"
  vars:
    dotfiles:
      - config/rclone/rclone.conf

- name: Install rsync.net shortcut script
  tags: rclone
  become: true
  ansible.builtin.copy:
    src: rsync.net
    dest: /usr/local/bin/rsync.net
    mode: "0755"
