---
# file managed by ansible-setup
# see https://k9scli.io/topics/hotkeys/
hotKeys:
  shift-1:
    shortCut: Shift-1
    description: show namespaces
    command: namespaces

  # problem with this one, see https://github.com/derailed/k9s/issues/2724
  shift-2:
    shortCut: Shift-2
    description: show deployments
    command: dp
