---
- name: setup for a laptop in a work environment
  hosts: localhost
  roles:
    - { role: common }
    - { role: dotfiles }
    - { role: ssh }
    - { role: desktop }
    - { role: git, tags: [git] }
    - { role: python, tags: [dev, python] }
    - { role: debian }
    - { role: wmf }
    - { role: k8s }
