---
- name: Setup for a laptop in a work environment
  hosts: localhost
  handlers:
    - name: Import handlers
      ansible.builtin.import_tasks: ../handlers/main.yml
  vars_files:
    - ../vars/k8s.yaml
  roles:
    - { role: common }
    # disabled for now, libvirtd requires a restart everytimg I interact with it
    #- { role: libvirt }
    - { role: nftables }
    - { role: dotfiles }
    - { role: ssh }
    - { role: desktop }
    - { role: git, tags: [git] }
    - { role: python, tags: [dev, python] }
    - { role: golang }
    - { role: debian }
    - { role: netfilter }
    - { role: wmf }
    - { role: k8s }
