---
- name: setup for a laptop in a work environment
  hosts: localhost
  roles:
    - { role: common, become: true }
    - { role: dotfiles, become: true }
    - { role: ssh, become: true }
    - { role: desktop, become: true }
    - { role: git, become: true, tags: [git] }
    - { role: python, become: true, tags: [dev, python] }
    - { role: debian, become: true }
    - { role: wmf, become: true }
    - { role: k8s, become: true }
