---
- name: setup for a laptop in a work environment
  hosts: localhost
  handlers:
    - import_tasks: ../handlers/main.yml
  vars_files:
    - ../vars/k8s.yaml
  roles:
    - { role: common }
    - { role: libvirt }
    - { role: nftables }
    - { role: dotfiles }
    - { role: ssh }
    - { role: desktop }
    - { role: git, tags: [git] }
    - { role: python, tags: [dev, python] }
    - { role: debian }
    - { role: netfilter }
    - { role: wmf }
    - { role: k8s }
