---
- name: setup for a laptop in a work environment
  hosts:
    localhost
  roles:
    - { role: common, become: yes }
    - { role: dotfiles, become: yes }
    - { role: ssh, become: yes }
    - { role: desktop, become: yes }
    - { role: git, become: yes, tags: [ 'git' ] }
    - { role: python, become: yes, tags: [ 'dev', 'python' ] }
    - { role: debian, become: yes }
    - { role: wmf, become: yes }
    - { role: k8s, become: yes }
