---
- name: setup for nostromo
  hosts: nostromo
  roles:
    - { role: common, become: yes }
    - { role: git, become: yes, tags: [ 'git' ] }
    - { role: python, become: yes, tags: [ 'dev', 'python' ] }
