# profiles for nostromo

- profile: pulseaudio_analog
  description: pulseaudio analog I/O profile
  setup:
    # set default sink, so sources move to it
    - pactl set-default-sink alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__sink
    # set the right card profile
    - pactl set-card-profile alsa_card.pci-0000_00_1f.3-platform-skl_hda_dsp_generic HiFi
    # enable playback on the analog sink
    - pactl suspend-sink @DEFAULT_SINK@ false
    # disable playback on the HDMI sink
    - pactl suspend-sink alsa_output.pci-0000_01_00.1.hdmi-stereo-extra1 true
    # select the right output (headphones instead of speakers)
    - pactl set-sink-port @DEFAULT_SINK@ Headphones
    # unmute and set output volume
    - pactl set-sink-mute @DEFAULT_SINK@ 0
    - pactl set-sink-volume @DEFAULT_SINK@ 80%
    # select the right source
    - pactl set-default-source alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__source
    # unmute and set mic volume
    - pactl set-source-mute @DEFAULT_SOURCE@ 0
    - pactl set-source-volume @DEFAULT_SOURCE@ 75%

- profile: pulseaudio_hdmi
  description: pulseaudio HDMI output profile
  setup:
    # set default sink, so sources move to it
    - pactl set-default-sink alsa_output.pci-0000_01_00.1.hdmi-stereo-extra1
    # set the right card profile
    - pactl set-card-profile alsa_card.pci-0000_01_00.1 output:hdmi-stereo-extra1
    # select the right HDMI port
    - pactl set-sink-port alsa_output.pci-0000_01_00.1.hdmi-stereo-extra1 hdmi-output-1
    # disable playback on the analog sink
    - pactl suspend-sink alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__sink true
    # enable playback on the HDMI sink
    - pactl suspend-sink alsa_output.pci-0000_01_00.1.hdmi-stereo-extra1 false
    # unmute and set volume
    - pactl set-sink-mute alsa_output.pci-0000_01_00.1.hdmi-stereo-extra1 0
    - pactl set-sink-volume @DEFAULT_SINK@ 40%
