# profiles for nostromo

- profile: pulseaudio_analog
  description: pulseaudio analog I/O profile
  setup:
    - echo "NOT IMPLEMENTED YET"

- profile: pulseaudio_hdmi
  description: pulseaudio HDMI output profile
  setup:
    - echo "NOT IMPLEMENTED YET"
