---
# profiles for nostromo

- profile: pulseaudio_analog
  description: pulseaudio analog I/O profile
  setup:
    # first: lower spotify volume, if running
    - |
      # spotify running?
      [ "$(ps aux | grep -i [s]potify | wc -l)" != "0" ] || return 0
      # get sink input index
      idx=$(pactl --format=json list sink-inputs | jq -rM '.[] | select(.properties."media.name" == "Spotify") | .index' | tail -1)
      [ "$idx" != "" ] || return 0
      pactl set-sink-input-volume "${idx}" 40%
    # then: the rest of the config. This order avoids the brief moment in which spotify running at max volume.
    # disable HDMI card
    - pactl set-card-profile alsa_card.pci-0000_01_00.1 off
    # disable docking station card
    - pactl set-card-profile alsa_card.usb-DisplayLink_USB3.0_5K_Graphic_Docking_4310338264599-02 off
    # configure the new card
    - pactl set-card-profile alsa_card.pci-0000_00_1f.3-platform-skl_hda_dsp_generic output:stereo-fallback+input:stereo-fallback
    - pactl set-default-sink alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.stereo-fallback
    - pactl suspend-sink alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.stereo-fallback false
    - pactl set-sink-port @DEFAULT_SINK@ 'analog-output-headphones'
    - pactl set-sink-mute @DEFAULT_SINK@ false
    - pactl set-sink-volume @DEFAULT_SINK@ 80%
    # configure the mic
    - pactl set-default-source alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.stereo-fallback
    - pactl set-source-port @DEFAULT_SOURCE@ 'analog-input-mic'
    - pactl set-source-volume @DEFAULT_SOURCE@ 80%
    - pactl set-source-mute @DEFAULT_SOURCE@ false


- profile: pulseaudio_hdmi
  description: pulseaudio HDMI output profile
  setup:
    # disable docking station card
    - pactl set-card-profile alsa_card.usb-DisplayLink_USB3.0_5K_Graphic_Docking_4310338264599-02 off
    # disable analog card
    - pactl set-card-profile alsa_card.pci-0000_00_1f.3-platform-skl_hda_dsp_generic off
    # configure the new card
    - pactl suspend-sink alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__sink true
    - pactl set-card-profile alsa_card.pci-0000_01_00.1 output:hdmi-stereo-extra1
    - pactl suspend-sink alsa_output.pci-0000_01_00.1.hdmi-stereo-extra1 false
    - pactl set-default-sink alsa_output.pci-0000_01_00.1.hdmi-stereo-extra1
    - pactl set-sink-port @DEFAULT_SINK@ hdmi-output-1
    - pactl set-sink-mute @DEFAULT_SINK@ false
    - pactl set-sink-volume @DEFAULT_SINK@ 60%
    # raise spotify volume, if running
    - |
      # spotify running?
      [ "$(ps aux | grep -i [s]potify | wc -l)" != "0" ] || return 0
      # get sink input index
      idx=$(pactl --format=json list sink-inputs | jq -rM '.[] | select(.properties."media.name" == "Spotify") | .index' | tail -1)
      [ "$idx" != "" ] || return 0
      pactl set-sink-input-volume "${idx}" 80%


- profile: pulseaudio_docking
  description: pulseaudio docking station output profile
  setup:
    # disable HDMI card
    - pactl set-card-profile alsa_card.pci-0000_01_00.1 off
    # disable analog card
    - pactl set-card-profile alsa_card.pci-0000_00_1f.3-platform-skl_hda_dsp_generic off
    # configure the new card
    - pactl set-card-profile alsa_card.usb-DisplayLink_USB3.0_5K_Graphic_Docking_4310338264599-02 output:analog-stereo+input:analog-stereo
    - pactl set-card-profile alsa_card.pci-0000_01_00.1 output:hdmi-stereo-extra1
    - pactl suspend-sink alsa_output.pci-0000_01_00.1.hdmi-stereo-extra1 false
    - pactl set-default-sink alsa_output.pci-0000_01_00.1.hdmi-stereo-extra1
    - pactl set-sink-port @DEFAULT_SINK@ analog-output-speaker
    - pactl set-sink-mute @DEFAULT_SINK@ false
    - pactl set-sink-volume @DEFAULT_SINK@ 60%
    # raise spotify volume, if running
    - |
      # spotify running?
      [ "$(ps aux | grep -i [s]potify | wc -l)" != "0" ] || return 0
      # get sink input index
      idx=$(pactl --format=json list sink-inputs | jq -rM '.[] | select(.properties."media.name" == "Spotify") | .index' | tail -1)
      [ "$idx" != "" ] || return 0
      pactl set-sink-input-volume "${idx}" 80%


- profile: screen_post_suspend
  description: enable & configure screen post laptop suspend
  setup:
    - chvt 7
    - DISPLAY=:0 xrandr --auto
    - DISPLAY=:0 xrandr -s 1920x1080
